import { AdrsList } from "@/app/[lang]/types/adr";

export const NanoassemblyAdrsList: AdrsList = [
    {
        translationKey: 'Use advanced manipulation and imaging tools',
        link: '/adrs/nano-assembly-adr/decisions/use-advanced-manipulation-and-imaging-tools',
        date: 'March 2026',
        status: 'Draft',
        
    },
    {
        translationKey: 'Use AI-driven system design',
        link: '/adrs/nano-assembly-adr/decisions/use-ai-driven-system-design',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use atomic resolution imaging in dynamic environments',
        link: '/adrs/nano-assembly-adr/decisions/use-atomic-resolution-imaging-in-dynamic-environments',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use bio-nano interfaces and safety',
        link: '/adrs/nano-assembly-adr/decisions/use-bio-nano-interfaces-and-safety',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use computing and AI breakthroughs',
        link: '/adrs/nano-assembly-adr/decisions/use-computing-and-ai-breakthroughs',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use diamondoid and stiff nanostructures',
        link: '/adrs/nano-assembly-adr/decisions/use-diamondoid-and-stiff-nanostructures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use efficient nano energy sources',
        link: '/adrs/nano-assembly-adr/decisions/use-efficient-nano-energy-sources',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use energy and sustainability advances',
        link: '/adrs/nano-assembly-adr/decisions/use-energy-and-sustainability-advances',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use fundamental understanding of nanoscale physics and chemistry',
        link: '/adrs/nano-assembly-adr/decisions/use-fundamental-understanding-of-nanoscale-physics-and-chemistry',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use hierarchical assembly protocols',
        link: '/adrs/nano-assembly-adr/decisions/use-hierarchical-assembly-protocols',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use high-throughput nanomanipulation',
        link: '/adrs/nano-assembly-adr/decisions/use-high-throughput-nanomanipulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use integration with biological systems',
        link: '/adrs/nano-assembly-adr/decisions/use-integration-with-biological-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use materials science innovations',
        link: '/adrs/nano-assembly-adr/decisions/use-materials-science-innovations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use mechanosynthesis mastery',
        link: '/adrs/nano-assembly-adr/decisions/use-mechanosynthesis-mastery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use novel feedstock processing',
        link: '/adrs/nano-assembly-adr/decisions/use-novel-feedstock-processing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use quantum computing for simulations',
        link: '/adrs/nano-assembly-adr/decisions/use-quantum-computing-for-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use quantum effects at macro scales',
        link: '/adrs/nano-assembly-adr/decisions/use-quantum-effects-at-macro-scales',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use reliable self-replication',
        link: '/adrs/nano-assembly-adr/decisions/use-reliable-self-replication',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use safety protocols for bio-nano interfaces',
        link: '/adrs/nano-assembly-adr/decisions/use-safety-protocols-for-bio-nano-interfaces',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use self-healing and adaptive materials',
        link: '/adrs/nano-assembly-adr/decisions/use-self-healing-and-adaptive-materials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use self-replication and scaling mechanisms',
        link: '/adrs/nano-assembly-adr/decisions/use-self-replication-and-scaling-mechanisms',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use swarm intelligence algorithms',
        link: '/adrs/nano-assembly-adr/decisions/use-swarm-intelligence-algorithms',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use unified nanotheory',
        link: '/adrs/nano-assembly-adr/decisions/use-unified-nanotheory',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use zero waste recycling',
        link: '/adrs/nano-assembly-adr/decisions/use-zero-waste-recycling',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Define hardware sufficient for nano-assembly computing tasks',
        link: '/adrs/nano-assembly-adr/decisions/define-hardware-sufficient-for-nano-assembly-computing',
        date: 'April 2026',
        status: 'Draft',
    },
];