// // mdx-components.tsx
// "use client";

// import type { MDXComponents } from "mdx/types";
// import CodeBlock from "@/app/[lang]/components/CodeBlock";
// import MathBlock from "@/app/[lang]/components/MathBlock";
// import React from "react";

// type Dictionary = Record<string, string>;

// export function getMDXComponents(dict: Dictionary = {}): MDXComponents {
//   return {
//     pre: (props: any) => <CodeBlock {...props} />,

//     T: ({
//       id,
//       ...props
//     }: { id: string } & React.HTMLAttributes<HTMLSpanElement>) => (
//       <span {...props}>{dict[id] ?? id}</span>
//     ),
//     // Intercept block-level formulas generated by MathJax using a dynamic element factory
//     "mjx-container": (props: any) => {
//       // Only wrap standalone block equations (display="true"), keep inline formulas ($...$) un-wrapped
//       if (props.display === "true") {
//         return <MathBlock {...props} />;
//       }

//       // Dynamic rendering bypasses JSX.IntrinsicElements validation limits
//       return React.createElement("mjx-container", props);
//     },
//   };
// }

"use client";

import type { MDXComponents } from "mdx/types";
import CodeBlock from "@/app/[lang]/components/CodeBlock";
import MathBlock from "@/app/[lang]/components/MathBlock"; // Import the component

type Dictionary = Record<string, string>;

export function getMDXComponents(dict: Dictionary = {}): MDXComponents {
  return {
    pre: (props: any) => <CodeBlock {...props} />,
    T: ({
      id,
      ...props
    }: { id: string } & React.HTMLAttributes<HTMLSpanElement>) => (
      <span {...props}>{dict[id] ?? id}</span>
    ),

    // Register the component directly.
    // This leaves standard $$...$$ formulas alone while enabling <MathBlock> triggers.
    MathBlock,
  };
}
