// app/[lang]/components/MDXContent.tsx
// "use client";

// import { MDXRemote } from "next-mdx-remote/rsc";
// import rehypePrettyCode from "rehype-pretty-code";

// import moonlightTheme from "@/public/assets/moonlight-ii.json" with { type: "json" };
// import CodeBlock from "./CodeBlock";

// const rehypePrettyCodeOptions = {
//   keepBackground: false,
//   theme: moonlightTheme,
//   grid: false,
// };

// type Props = {
//   source: string;
//   dict?: Record<string, string>;
// };

// export default function MDXContent({ source, dict = {} }: Props) {
//   return (
//     <MDXRemote
//       source={source}
//       options={{
//         mdxOptions: {
//           rehypePlugins: [[rehypePrettyCode, rehypePrettyCodeOptions]],
//         },
//       }}
//       components={{
//         pre: (props: any) => <CodeBlock {...props} />,
//         T: ({
//           id,
//           ...props
//         }: { id: string } & React.HTMLAttributes<HTMLSpanElement>) => (
//           <span {...props}>{dict[id] ?? id}</span>
//         ),
//       }}
//     />
//   );
// }

"use client";
import { MDXRemote } from "next-mdx-remote/rsc";
import rehypePrettyCode from "rehype-pretty-code";
import remarkMath from "remark-math";
import rehypeMathjax from "rehype-mathjax";
import moonlightTheme from "@/public/assets/moonlight-ii.json" with { type: "json" };
import CodeBlock from "./CodeBlock";
import MathBlock from "@/app/[lang]/components/MathBlock";
import React from "react";

const rehypePrettyCodeOptions = {
  keepBackground: false,
  theme: moonlightTheme,
  grid: false,
};

type Props = {
  source: string;
  dict?: Record<string, string>;
};

export default function MDXContent({ source, dict = {} }: Props) {
  return (
    <MDXRemote
      source={source}
      options={{
        mdxOptions: {
          remarkPlugins: [remarkMath],
          rehypePlugins: [
            [rehypePrettyCode, rehypePrettyCodeOptions],
            rehypeMathjax,
          ],
        },
      }}
      components={{
        pre: (props: any) => <CodeBlock {...props} />,
        T: ({
          id,
          ...props
        }: { id: string } & React.HTMLAttributes<HTMLSpanElement>) => (
          <span {...props}>{dict[id] ?? id}</span>
        ),
        // INTERCEPT BLOCK MATH: Map standard display divs to your new MathBlock card
        div: (props: any) => {
          if (props.className?.includes("math-display")) {
            return <MathBlock {...props} />;
          }
          return <div {...props} />;
        },
        // Intercept block-level formulas generated by MathJax using a dynamic element factory
        // "mjx-container": (props: any) => {
        //   // Only wrap standalone block equations (display="true"), keep inline formulas ($...$) un-wrapped
        //   if (props.display === "true") {
        //     return <MathBlock {...props} />;
        //   }

        //   // Dynamic rendering bypasses JSX.IntrinsicElements validation limits
        //   return React.createElement("mjx-container", props);
        // },
        MathBlock,
      }}
    />
  );
}
