import { AdrsList } from "@/app/[lang]/types/adr";

export const StarshipNanoassemblyAdrsList: AdrsList = [
    {
        translationKey: 'Preparation and feedstock acquisition',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Preparation and feedstock acquisition: Raw Material Gathering',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition-raw-material-gathering',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Preparation and feedstock acquisition: Design Input',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition-design-input',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Preparation and feedstock acquisition: Seed Nanobot Deployment',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition-seed-nanobot-deployment',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanobot replication and swarm formation',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanobot replication and swarm formation: Exponential Scaling',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation-exponential-scaling',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanobot replication and swarm formation: Coordination Setup',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation-coordination-setup',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanobot replication and swarm formation: Site Preparation',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation-site-preparation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Bottom-up Component Assembly',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Bottom-up component assembly: Super Heavy Booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building The Super Heavy Booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Super Heavy Booster: Engine Integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-super-heavy-booster-engine-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Super Heavy Booster: Engines and Systems',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-super-heavy-booster-engines-and-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Super Heavy Booster: Interior Features',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-super-heavy-booster-interior-features',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Super Heavy Booster: Structural Skeleton',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-super-heavy-booster-structural-skeleton',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Super Heavy Booster: Tank and Insulation',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-super-heavy-booster-tank-and-insulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building The Super Heavy Booster: Engine Integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster-engine-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building The Super Heavy Booster: Structural Skeleton',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster-structural-skeleton',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building The Super Heavy Booster: Tank and Insulation',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster-tank-and-insulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Bottom-up component assembly: Starship Upper Stage',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-starship-upper-stage',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Starship Upper Stage: Structural Skeleton',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-starship-upper-stage-structural-skeleton',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Starship Upper Stage: Interior Features',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-starship-upper-stage-interior-features',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Starship Upper Stage: Tank and Insulation',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-starship-upper-stage-tank-and-insulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Starship Upper Stage: Engine Integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-starship-upper-stage-engine-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Starship Upper Stage: Hull and Heat Shield',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-starship-upper-stage-hull-and-heat-shield',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Building Starship Upper Stage: Engines and Systems',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-building-starship-upper-stage-engines-and-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Super Heavy Booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Super Heavy Booster: Stacking the Stages',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster-stacking-the-stages',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Super Heavy Booster: System Wide Integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster-system-wide-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Super Heavy Booster: Quality Assurance',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster-quality-assurance',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Starship Upper Stage',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Starship Upper Stage: Stacking the Stages',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage-stacking-the-stages',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Starship Upper Stage: System Wide Integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage-system-wide-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration and Final Assembly: Starship Upper Stage: Quality Assurance',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage-quality-assurance',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Super Heavy Booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Super Heavy Booster: Fueling and Activation',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster-fueling-and-activation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Super Heavy Booster: Post-Assembly',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster-post-assembly',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Super Heavy Booster: Scalability',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster-scalability',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Starship Upper Stage',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Starship Upper Stage: Fueling and Activation',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage-fueling-and-activation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Starship Upper Stage: Post-Assembly',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage-post-assembly',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Completion and Launch Readiness: Starship Upper Stage: Scalability',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage-scalability',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full monolithically grown Starship with MNT',
        link: '/adrs/starship-nano-assembly-adr/decisions/full-monolithically-grown-starship-with-mnt',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full Starship Assembly Using MNT',
        link: '/adrs/starship-nano-assembly-adr/decisions/full-starship-assembly-using-mnt',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration of Starship from Nanoassembled Components',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-of-starship-from-nanoassembled-components',
        date: 'March 2026',
        status: 'Draft',
    },
];