import { AdrsList } from "@/app/[lang]/types/adr";

export const StarshipNanoassemblyAdrsList: AdrsList = [
    {
        translationKey: 'preparation-and-feedstock-acquisition',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'preparation-and-feedstock-acquisition-raw-material-gathering',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition-raw-material-gathering',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'preparation-and-feedstock-acquisition-design-input',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition-design-input',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'preparation-and-feedstock-acquisition-seed-nanobot-deployment',
        link: '/adrs/starship-nano-assembly-adr/decisions/preparation-and-feedstock-acquisition-seed-nanobot-deployment',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanobot-replication-and-swarm-formation',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanobot-replication-and-swarm-formation-exponential-scaling',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation-exponential-scaling',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanobot-replication-and-swarm-formation-coordination-setup',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation-coordination-setup',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanobot-replication-and-swarm-formation-site-preparation',
        link: '/adrs/starship-nano-assembly-adr/decisions/nanobot-replication-and-swarm-formation-site-preparation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'bottom-up-component-assembly',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'bottom-up-component-assembly-super-heavy-booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/bottom-up-component-assembly-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'building-the-super-heavy-booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'building-the-super-heavy-booster-engine-integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster-engine-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'building-the-super-heavy-booster-structural-skeleton',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster-structural-skeleton',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'building-the-super-heavy-booster-tank-and-insulation',
        link: '/adrs/starship-nano-assembly-adr/decisions/building-the-super-heavy-booster-tank-and-insulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-super-heavy-booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-super-heavy-booster-stacking-the-stages',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster-stacking-the-stages',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-super-heavy-booster-system-wide-integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster-system-wide-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-super-heavy-booster-quality-assurance',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-super-heavy-booster-quality-assurance',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-starship-upper-stage',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-starship-upper-stage-stacking-the-stages',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage-stacking-the-stages',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-starship-upper-stage-system-wide-integration',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage-system-wide-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-and-final-assembly-starship-upper-stage-quality-assurance',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-and-final-assembly-starship-upper-stage-quality-assurance',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-super-heavy-booster',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-super-heavy-booster-fueling-and-activation',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster-fueling-and-activation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-super-heavy-booster-post-assembly',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster-post-assembly',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-super-heavy-booster-scalability',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-super-heavy-booster-scalability',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-starship-upper-stage',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-starship-upper-stage-fueling-and-activation',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage-fueling-and-activation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-starship-upper-stage-post-assembly',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage-post-assembly',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'completion-and-launch-readiness-starship-upper-stage-scalability',
        link: '/adrs/starship-nano-assembly-adr/decisions/completion-and-launch-readiness-starship-upper-stage-scalability',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-monolithically-grown-starship-with-mnt',
        link: '/adrs/starship-nano-assembly-adr/decisions/full-monolithically-grown-starship-with-mnt',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-starship-assembly-using-mnt',
        link: '/adrs/starship-nano-assembly-adr/decisions/full-starship-assembly-using-mnt',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-of-starship-from-nanoassembled-components',
        link: '/adrs/starship-nano-assembly-adr/decisions/integration-of-starship-from-nanoassembled-components',
        date: 'March 2026',
        status: 'Draft',
    },
];