import { AdrsList } from "@/app/[lang]/types/adr";

export const OptimusAdrsList: AdrsList = [
    {
        translationKey: 'Hardware Components',
        link: '/adrs/optimus-adr/decisions/hardware-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Mechanical Components',
        link: '/adrs/optimus-adr/decisions/mechanical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Electrical Components',
        link: '/adrs/optimus-adr/decisions/electrical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Power Components',
        link: '/adrs/optimus-adr/decisions/power-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensing Components',
        link: '/adrs/optimus-adr/decisions/sensing-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Compute Components',
        link: '/adrs/optimus-adr/decisions/compute-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Structural & Mechanical Components',
        link: '/adrs/optimus-adr/decisions/structural-mechanical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full-body skeleton',
        link: '/adrs/optimus-adr/decisions/full-body-skeleton',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Joint mechanisms with appropriate range of motion',
        link: '/adrs/optimus-adr/decisions/joint-mechanisms',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Hands',
        link: '/adrs/optimus-adr/decisions/hands',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Feet',
        link: '/adrs/optimus-adr/decisions/feet',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Protective outer skin/shell',
        link: '/adrs/optimus-adr/decisions/protective-outer-skin-shell',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'CAD models, finite element analysis (FEA)',
        link: '/adrs/optimus-adr/decisions/cad-models-finite-element-analysis',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Actuation System, (Core of Movement)',
        link: '/adrs/optimus-adr/decisions/actuation-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Movement',
        link: '/adrs/optimus-adr/decisions/movement',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Body actuators',
        link: '/adrs/optimus-adr/decisions/body-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Hand actuators',
        link: '/adrs/optimus-adr/decisions/hand-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Motor drivers',
        link: '/adrs/optimus-adr/decisions/motor-drivers',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Current/torque sensing',
        link: '/adrs/optimus-adr/decisions/current-torque-sensing',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Thermal management',
        link: '/adrs/optimus-adr/decisions/thermal-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Fail-safes',
        link: '/adrs/optimus-adr/decisions/fail-safes',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Encoders (for redundancy and precision ?)',
        link: '/adrs/optimus-adr/decisions/encoders-for-redundancy-and-precision',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Elastic elements for safe human interaction (?)',
        link: '/adrs/optimus-adr/decisions/elastic-elements-for-safe-human-interaction',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensing & Perception Hardware',
        link: '/adrs/optimus-adr/decisions/sensing-and-perception-hardware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Vision system',
        link: '/adrs/optimus-adr/decisions/vision-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Inertial Measurement Units (IMUs)',
        link: '/adrs/optimus-adr/decisions/inertial-measurement-units-imus',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensors (for proprioception ?)',
        link: '/adrs/optimus-adr/decisions/sensors-for-propriocption',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Power & Energy Management',
        link: '/adrs/optimus-adr/decisions/power-energy-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Battery',
        link: '/adrs/optimus-adr/decisions/battery',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Power electronics',
        link: '/adrs/optimus-adr/decisions/power-electronics',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Embedded Electronics & Compute Hardware',
        link: '/adrs/optimus-adr/decisions/embedded-electronics-compute-hardware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'High-performance SoC or modular compute board with AI accelerators',
        link: '/adrs/optimus-adr/decisions/high-performance-soc-or-modular-compute-board-with-ai-accelerators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Distributed motor controller PCBs',
        link: '/adrs/optimus-adr/decisions/distributed-motor-controller-pcbs',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Software Components',
        link: '/adrs/optimus-adr/decisions/software-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Low-Level Firmware & Real-Time Control',
        link: '/adrs/optimus-adr/decisions/low-level-firmware-real-time-control',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Actuator firmware',
        link: '/adrs/optimus-adr/decisions/actuator-firmware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Communication protocols and drivers for all buses/sensors',
        link: '/adrs/optimus-adr/decisions/communication-protocols-and-drivers-for-all-buses-sensors',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Operating System',
        link: '/adrs/optimus-adr/decisions/operating-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Kinematics, Dynamics & Control Stack',
        link: '/adrs/optimus-adr/decisions/kinematics-dynamics-control-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Forward/inverse kinematics and dynamics libraries',
        link: '/adrs/optimus-adr/decisions/forward-inverse-kinematics-and-dynamics-libraries',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Locomotion stack (e.g., walking, running, climbing), whole-body control',
        link: '/adrs/optimus-adr/decisions/locomotion-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Manipulation stack (object handling, tool use), dexterity',
        link: '/adrs/optimus-adr/decisions/manipulation-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Perception Stack',
        link: '/adrs/optimus-adr/decisions/perception-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Computer vision',
        link: '/adrs/optimus-adr/decisions/computer-vision',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensor fusion',
        link: '/adrs/optimus-adr/decisions/sensor-fusion',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Vision-based navigation and mapping',
        link: '/adrs/optimus-adr/decisions/vision-based-navigation-and-mapping',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'High-Level AI, Planning & Autonomy',
        link: '/adrs/optimus-adr/decisions/high-level-ai-planning-autonomy',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Task planning and reasoning',
        link: '/adrs/optimus-adr/decisions/task-planning-and-reasoning',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Learning',
        link: '/adrs/optimus-adr/decisions/learning',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration with AI Models (e.g., for perception, decision-making, human-robot interaction), etc. (?)',
        link: '/adrs/optimus-adr/decisions/integration-with-ai-models',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Multi-robot coordination and fleet management',
        link: '/adrs/optimus-adr/decisions/multi-robot-coordination-and-fleet-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Simulation, Training & Data Pipeline',
        link: '/adrs/optimus-adr/decisions/simulation-training-data-pipeline',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Physics-based simulator',
        link: '/adrs/optimus-adr/decisions/physics-based-simulator',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Data collection, labeling, and training',
        link: '/adrs/optimus-adr/decisions/data-collection-labeling-and-training',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Teleoperation and human-in-the-loop training tools',
        link: '/adrs/optimus-adr/decisions/teleoperation-and-human-in-the-loop-training-tools',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Safety, Diagnostics & Human-Robot Interaction (HRI)',
        link: '/adrs/optimus-adr/decisions/safety-diagnostics-human-robot-interaction-hri',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Collision avoidance',
        link: '/adrs/optimus-adr/decisions/collision-avoidance',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Diagnostics, logging, and over-the-air (OTA) update system',
        link: '/adrs/optimus-adr/decisions/diagnostics-logging-and-ota-update-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'HRI: voice/gesture recognition, facial expression/screen interface, natural language understanding',
        link: '/adrs/optimus-adr/decisions/hri-voice-gesture-recognition-facial-expression-screen-interface-natural-language-understanding',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Supporting Software/Tools',
        link: '/adrs/optimus-adr/decisions/supporting-software-tools',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Calibration tools for sensors and actuators (e.g., for accurate kinematics, force control)',
        link: '/adrs/optimus-adr/decisions/calibration-tools-for-sensors-and-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Development/debugging tools, visualization and testing frameworks',
        link: '/adrs/optimus-adr/decisions/development-debugging-tools-visualization-and-testing-frameworks',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Documentation, build systems, and CI/CD for open-source community contributions',
        link: '/adrs/optimus-adr/decisions/documentation-build-systems-and-cicd-for-open-source-community-contributions',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration & System-Level Testing',
        link: '/adrs/optimus-adr/decisions/integration-system-level-testing',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Whole-robot assembly',
        link: '/adrs/optimus-adr/decisions/whole-robot-assembly',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Tuning (balance, gait, manipulation), and validation in real environments',
        link: '/adrs/optimus-adr/decisions/tuning-and-validation-in-real-environments',
        date: 'May 2026',
        status: 'Draft',
    },
];