import { AdrsList } from "@/app/[lang]/types/adr";

export const OptimusAdrsList: AdrsList = [
    {
        translationKey: 'hardware-components',
        link: '/adrs/optimus-adr/decisions/hardware-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'mechanical-components',
        link: '/adrs/optimus-adr/decisions/mechanical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'electrical-components',
        link: '/adrs/optimus-adr/decisions/electrical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'power-components',
        link: '/adrs/optimus-adr/decisions/power-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensing-components',
        link: '/adrs/optimus-adr/decisions/sensing-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'compute-components',
        link: '/adrs/optimus-adr/decisions/compute-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'structural-mechanical-components',
        link: '/adrs/optimus-adr/decisions/structural-mechanical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-body-skeleton',
        link: '/adrs/optimus-adr/decisions/full-body-skeleton',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'joint-mechanisms',
        link: '/adrs/optimus-adr/decisions/joint-mechanisms',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'hands',
        link: '/adrs/optimus-adr/decisions/hands',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'feet',
        link: '/adrs/optimus-adr/decisions/feet',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'protective-outer-skin-shell',
        link: '/adrs/optimus-adr/decisions/protective-outer-skin-shell',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'cad-models-finite-element-analysis',
        link: '/adrs/optimus-adr/decisions/cad-models-finite-element-analysis',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'actuation-system',
        link: '/adrs/optimus-adr/decisions/actuation-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'movement',
        link: '/adrs/optimus-adr/decisions/movement',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'body-actuators',
        link: '/adrs/optimus-adr/decisions/body-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'hand-actuators',
        link: '/adrs/optimus-adr/decisions/hand-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'motor-drivers',
        link: '/adrs/optimus-adr/decisions/motor-drivers',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'current-torque-sensing',
        link: '/adrs/optimus-adr/decisions/current-torque-sensing',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'thermal-management',
        link: '/adrs/optimus-adr/decisions/thermal-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fail-safes',
        link: '/adrs/optimus-adr/decisions/fail-safes',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'encoders-for-redundancy-and-precision',
        link: '/adrs/optimus-adr/decisions/encoders-for-redundancy-and-precision',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'elastic-elements-for-safe-human-interaction',
        link: '/adrs/optimus-adr/decisions/elastic-elements-for-safe-human-interaction',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensing-and-perception-hardware',
        link: '/adrs/optimus-adr/decisions/sensing-and-perception-hardware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'vision-system',
        link: '/adrs/optimus-adr/decisions/vision-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'inertial-measurement-units-imus',
        link: '/adrs/optimus-adr/decisions/inertial-measurement-units-imus',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensors-for-propriocption',
        link: '/adrs/optimus-adr/decisions/sensors-for-proprioception',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'power-energy-management',
        link: '/adrs/optimus-adr/decisions/power-energy-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'battery',
        link: '/adrs/optimus-adr/decisions/battery',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'power-electronics',
        link: '/adrs/optimus-adr/decisions/power-electronics',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'embedded-electronics-compute-hardware',
        link: '/adrs/optimus-adr/decisions/embedded-electronics-compute-hardware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-performance-soc-or-modular-compute-board-with-ai-accelerators',
        link: '/adrs/optimus-adr/decisions/high-performance-soc-or-modular-compute-board-with-ai-accelerators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'distributed-motor-controller-pcbs',
        link: '/adrs/optimus-adr/decisions/distributed-motor-controller-pcbs',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'software-components',
        link: '/adrs/optimus-adr/decisions/software-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'low-level-firmware-real-time-control',
        link: '/adrs/optimus-adr/decisions/low-level-firmware-real-time-control',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'actuator-firmware',
        link: '/adrs/optimus-adr/decisions/actuator-firmware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'communication-protocols-and-drivers-for-all-buses-sensors',
        link: '/adrs/optimus-adr/decisions/communication-protocols-and-drivers-for-all-buses-sensors',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'operating-system',
        link: '/adrs/optimus-adr/decisions/operating-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'kinematics-dynamics-control-stack',
        link: '/adrs/optimus-adr/decisions/kinematics-dynamics-control-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'forward-inverse-kinematics-and-dynamics-libraries',
        link: '/adrs/optimus-adr/decisions/forward-inverse-kinematics-and-dynamics-libraries',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'locomotion-stack',
        link: '/adrs/optimus-adr/decisions/locomotion-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'manipulation-stack',
        link: '/adrs/optimus-adr/decisions/manipulation-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'perception-stack',
        link: '/adrs/optimus-adr/decisions/perception-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'computer-vision',
        link: '/adrs/optimus-adr/decisions/computer-vision',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensor-fusion',
        link: '/adrs/optimus-adr/decisions/sensor-fusion',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'vision-based-navigation-and-mapping',
        link: '/adrs/optimus-adr/decisions/vision-based-navigation-and-mapping',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-level-ai-planning-autonomy',
        link: '/adrs/optimus-adr/decisions/high-level-ai-planning-autonomy',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'task-planning-and-reasoning',
        link: '/adrs/optimus-adr/decisions/task-planning-and-reasoning',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'learning',
        link: '/adrs/optimus-adr/decisions/learning',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-with-ai-models',
        link: '/adrs/optimus-adr/decisions/integration-with-ai-models',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'multi-robot-coordination-and-fleet-management',
        link: '/adrs/optimus-adr/decisions/multi-robot-coordination-and-fleet-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'simulation-training-data-pipeline',
        link: '/adrs/optimus-adr/decisions/simulation-training-data-pipeline',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'physics-based-simulator',
        link: '/adrs/optimus-adr/decisions/physics-based-simulator',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'data-collection-labeling-and-training',
        link: '/adrs/optimus-adr/decisions/data-collection-labeling-and-training',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'teleoperation-and-human-in-the-loop-training-tools',
        link: '/adrs/optimus-adr/decisions/teleoperation-and-human-in-the-loop-training-tools',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'safety-diagnostics-human-robot-interaction-hri',
        link: '/adrs/optimus-adr/decisions/safety-diagnostics-human-robot-interaction-hri',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'collision-avoidance',
        link: '/adrs/optimus-adr/decisions/collision-avoidance',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'diagnostics-logging-and-ota-update-system',
        link: '/adrs/optimus-adr/decisions/diagnostics-logging-and-ota-update-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'hri-voice-gesture-recognition-facial-expression-screen-interface-natural-language-understanding',
        link: '/adrs/optimus-adr/decisions/hri-voice-gesture-recognition-facial-expression-screen-interface-natural-language-understanding',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'supporting-software-tools',
        link: '/adrs/optimus-adr/decisions/supporting-software-tools',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'calibration-tools-for-sensors-and-actuators',
        link: '/adrs/optimus-adr/decisions/calibration-tools-for-sensors-and-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'development-debugging-tools-visualization-and-testing-frameworks',
        link: '/adrs/optimus-adr/decisions/development-debugging-tools-visualization-and-testing-frameworks',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'documentation-build-systems-and-cicd-for-open-source-community-contributions',
        link: '/adrs/optimus-adr/decisions/documentation-build-systems-and-cicd-for-open-source-community-contributions',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-system-level-testing',
        link: '/adrs/optimus-adr/decisions/integration-system-level-testing',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'whole-robot-assembly',
        link: '/adrs/optimus-adr/decisions/whole-robot-assembly',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        translationKey: 'tuning-and-validation-in-real-environments',
        link: '/adrs/optimus-adr/decisions/tuning-and-validation-in-real-environments',
        date: 'May 2026',
        status: 'Draft',
    },
];