import { AdrsList } from "@/app/[lang]/types/adr";

export const OptimusAdrsList: AdrsList = [
    {
        title: 'Hardware Components',
        link: '/adrs/optimus-adr/hardware-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Mechanical Components',
        link: '/adrs/optimus-adr/mechanical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Electrical Components',
        link: '/adrs/optimus-adr/electrical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Power Components',
        link: '/adrs/optimus-adr/power-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Sensing Components',
        link: '/adrs/optimus-adr/sensing-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Compute Components',
        link: '/adrs/optimus-adr/compute-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Structural & Mechanical Components',
        link: '/adrs/optimus-adr/structural-mechanical-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Full-body skeleton',
        link: '/adrs/optimus-adr/full-body-skeleton',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Joint mechanisms with appropriate range of motion',
        link: '/adrs/optimus-adr/joint-mechanisms',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Hands',
        link: '/adrs/optimus-adr/hands',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Feet',
        link: '/adrs/optimus-adr/feet',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Protective outer skin/shell',
        link: '/adrs/optimus-adr/protective-outer-skin-shell',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'CAD models, finite element analysis (FEA)',
        link: '/adrs/optimus-adr/cad-models-finite-element-analysis',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Actuation System, (Core of Movement)',
        link: '/adrs/optimus-adr/actuation-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Movement',
        link: '/adrs/optimus-adr/movement',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Body actuators',
        link: '/adrs/optimus-adr/body-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Hand actuators',
        link: '/adrs/optimus-adr/hand-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Motor drivers',
        link: '/adrs/optimus-adr/motor-drivers',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Current/torque sensing',
        link: '/adrs/optimus-adr/current-torque-sensing',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Thermal management',
        link: '/adrs/optimus-adr/thermal-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Fail-safes',
        link: '/adrs/optimus-adr/fail-safes',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Encoders (for redundancy and precision ?)',
        link: '/adrs/optimus-adr/encoders-for-redundancy-and-precision',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Elastic elements for safe human interaction (?)',
        link: '/adrs/optimus-adr/elastic-elements-for-safe-human-interaction',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Sensing & Perception Hardware',
        link: '/adrs/optimus-adr/sensing-and-perception-hardware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Vision system',
        link: '/adrs/optimus-adr/vision-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Inertial Measurement Units (IMUs)',
        link: '/adrs/optimus-adr/inertial-measurement-units-imus',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Sensors (for proprioception ?)',
        link: '/adrs/optimus-adr/sensors-for-propriocption',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Power & Energy Management',
        link: '/adrs/optimus-adr/power-energy-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Battery',
        link: '/adrs/optimus-adr/battery',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Power electronics',
        link: '/adrs/optimus-adr/power-electronics',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Embedded Electronics & Compute Hardware',
        link: '/adrs/optimus-adr/embedded-electronics-compute-hardware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'High-performance SoC or modular compute board with AI accelerators',
        link: '/adrs/optimus-adr/high-performance-soc-or-modular-compute-board-with-ai-accelerators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Distributed motor controller PCBs',
        link: '/adrs/optimus-adr/distributed-motor-controller-pcbs',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Software Components',
        link: '/adrs/optimus-adr/software-components',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Low-Level Firmware & Real-Time Control',
        link: '/adrs/optimus-adr/low-level-firmware-real-time-control',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Actuator firmware',
        link: '/adrs/optimus-adr/actuator-firmware',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Communication protocols and drivers for all buses/sensors',
        link: '/adrs/optimus-adr/communication-protocols-and-drivers-for-all-buses-sensors',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Operating System',
        link: '/adrs/optimus-adr/operating-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Kinematics, Dynamics & Control Stack',
        link: '/adrs/optimus-adr/kinematics-dynamics-control-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Forward/inverse kinematics and dynamics libraries',
        link: '/adrs/optimus-adr/forward-inverse-kinematics-and-dynamics-libraries',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Locomotion stack (e.g., walking, running, climbing), whole-body control',
        link: '/adrs/optimus-adr/locomotion-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Manipulation stack (object handling, tool use), dexterity',
        link: '/adrs/optimus-adr/manipulation-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Perception Stack',
        link: '/adrs/optimus-adr/perception-stack',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Computer vision',
        link: '/adrs/optimus-adr/computer-vision',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Sensor fusion',
        link: '/adrs/optimus-adr/sensor-fusion',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Vision-based navigation and mapping',
        link: '/adrs/optimus-adr/vision-based-navigation-and-mapping',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'High-Level AI, Planning & Autonomy',
        link: '/adrs/optimus-adr/high-level-ai-planning-autonomy',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Task planning and reasoning',
        link: '/adrs/optimus-adr/task-planning-and-reasoning',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Learning',
        link: '/adrs/optimus-adr/learning',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Integration with AI Models (e.g., for perception, decision-making, human-robot interaction), etc. (?)',
        link: '/adrs/optimus-adr/integration-with-ai-models',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Multi-robot coordination and fleet management',
        link: '/adrs/optimus-adr/multi-robot-coordination-and-fleet-management',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Simulation, Training & Data Pipeline',
        link: '/adrs/optimus-adr/simulation-training-data-pipeline',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Physics-based simulator',
        link: '/adrs/optimus-adr/physics-based-simulator',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Data collection, labeling, and training',
        link: '/adrs/optimus-adr/data-collection-labeling-and-training',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Teleoperation and human-in-the-loop training tools',
        link: '/adrs/optimus-adr/teleoperation-and-human-in-the-loop-training-tools',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Safety, Diagnostics & Human-Robot Interaction (HRI)',
        link: '/adrs/optimus-adr/safety-diagnostics-human-robot-interaction-hri',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Collision avoidance',
        link: '/adrs/optimus-adr/collision-avoidance',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Diagnostics, logging, and over-the-air (OTA) update system',
        link: '/adrs/optimus-adr/diagnostics-logging-and-ota-update-system',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'HRI: voice/gesture recognition, facial expression/screen interface, natural language understanding',
        link: '/adrs/optimus-adr/hri-voice-gesture-recognition-facial-expression-screen-interface-natural-language-understanding',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Supporting Software/Tools',
        link: '/adrs/optimus-adr/supporting-software-tools',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Calibration tools for sensors and actuators (e.g., for accurate kinematics, force control)',
        link: '/adrs/optimus-adr/calibration-tools-for-sensors-and-actuators',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Development/debugging tools, visualization and testing frameworks',
        link: '/adrs/optimus-adr/development-debugging-tools-visualization-and-testing-frameworks',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Documentation, build systems, and CI/CD for open-source community contributions',
        link: '/adrs/optimus-adr/documentation-build-systems-and-cicd-for-open-source-community-contributions',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Integration & System-Level Testing',
        link: '/adrs/optimus-adr/integration-system-level-testing',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Whole-robot assembly',
        link: '/adrs/optimus-adr/whole-robot-assembly',
        date: 'May 2026',
        status: 'Draft',
    },
    {
        title: 'Tuning (balance, gait, manipulation), and validation in real environments',
        link: '/adrs/optimus-adr/tuning-and-validation-in-real-environments',
        date: 'May 2026',
        status: 'Draft',
    },
];