import { AdrsList } from "@/app/[lang]/types/adr";

export const EngineeringSimulationToolAdrsList: AdrsList = [
    {
        translationKey: 'requirements',
        description: 'Description of Requirements',
        link: '/adrs/engineering-simulation-tool-adr/decisions/requirements',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'features',
        description: 'Description of Features',
        link: '/adrs/engineering-simulation-tool-adr/decisions/features',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'physics-engine',
        description: 'Description of Physics Engine',
        link: '/adrs/engineering-simulation-tool-adr/decisions/physics-engine',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'structural-analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/structural-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fluid-dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fluid-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'electromagnetics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/electromagnetics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: '3d-design-and-simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/3d-design-and-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'multiphysics-and-system-coupling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/multiphysics-and-system-coupling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'materials-and-data-management',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/materials-and-data-management',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integrated-geometry-modeling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/integrated-geometry-modeling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'interactive-topology-optimization',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/interactive-topology-optimization',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'real-time-simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/real-time-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: '3d-electromagnetic-field-solver',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/3d-electromagnetic-field-solver',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'analysis-of-electric-machines',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/analysis-of-electric-machines',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'electronics-reliability',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/electronics-reliability',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'low-frequency-simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/low-frequency-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'power-and-signal-integrity',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/power-and-signal-integrity',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'turbulence-modeling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/turbulence-modeling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'combustion-and-chemical-reactions',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/combustion-and-chemical-reactions',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'heat-transfer-conjugation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/heat-transfer-conjugation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'gpu-solver-acceleration',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/gpu-solver-acceleration',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'multiphase-flow-analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/multiphase-flow-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'overset-mesh',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/overset-mesh',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'material-design',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/material-design',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'materials-data',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/materials-data',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fluid-structure-interaction',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fluid-structure-interaction',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'thermal-structural-simulations',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/thermal-structural-simulations',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'twin-builder',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/twin-builder',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'composite-structure-analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/composite-structure-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'explicit-dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/explicit-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fatigue-analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fatigue-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fracture-and-crack-simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fracture-and-crack-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'linear-and-nonlinear-analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/linear-and-nonlinear-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'rigid-dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/rigid-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'topography-and-shape-optimization',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/topography-and-shape-optimization',
        date: 'April 2026',
        status: 'Draft',
    },
];