import { AdrsList } from "@/app/[lang]/types/adr";

export const EngineeringSimulationToolAdrsList: AdrsList = [
    {
        translationKey: 'Requirements',
        description: 'Description of Requirements',
        link: '/adrs/engineering-simulation-tool-adr/decisions/requirements',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Features',
        description: 'Description of Features',
        link: '/adrs/engineering-simulation-tool-adr/decisions/features',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Physics Engine',
        description: 'Description of Physics Engine',
        link: '/adrs/engineering-simulation-tool-adr/decisions/physics-engine',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Structural Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/structural-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Fluid dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fluid-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Electromagnetics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/electromagnetics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: '3D-Design and Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/3d-design-and-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Multiphysics and system coupling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/multiphysics-and-system-coupling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Materials and data management',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/materials-and-data-management',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integrated Geometry Modeling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/integrated-geometry-modeling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Interactive Topology Optimization',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/interactive-topology-optimization',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Real-time Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/real-time-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: '3D Electromagnetic Field Solver',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/3d-electromagnetic-field-solver',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Analysis of electric machines',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/analysis-of-electric-machines',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Electronics Reliability',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/electronics-reliability',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Low-Frequency Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/low-frequency-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Power & Signal Integrity',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/power-and-signal-integrity',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Turbulence Modeling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/turbulence-modeling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Combustion & Chemical Reactions',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/combustion-and-chemical-reactions',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Heat Transfer Conjugation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/heat-transfer-conjugation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'GPU Solver Acceleration',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/gpu-solver-acceleration',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Multiphase Flow Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/multiphase-flow-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Overset Mesh',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/overset-mesh',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Material Design',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/material-design',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Materials Data',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/materials-data',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Fluid-Structure Interaction',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fluid-structure-interaction',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Thermal-Structural Simulations',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/thermal-structural-simulations',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Twin Builder',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/twin-builder',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Composite Structure Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/composite-structure-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Explicit Dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/explicit-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Fatigue Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fatigue-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Fracture & Crack Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/fracture-and-crack-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Linear & Nonlinear Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/linear-and-nonlinear-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Rigid Dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/rigid-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Topography & Shape Optimization',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/decisions/topography-and-shape-optimization',
        date: 'April 2026',
        status: 'Draft',
    },
];