import { AdrsList } from "@/app/[lang]/types/adr";

export const EngineeringSimulationToolAdrsList: AdrsList = [
    {
        title: 'Requirements',
        description: 'Description of Requirements',
        link: '/adrs/engineering-simulation-tool-adr/requirements',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Features',
        description: 'Description of Features',
        link: '/adrs/engineering-simulation-tool-adr/features',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Physics Engine',
        description: 'Description of Physics Engine',
        link: '/adrs/engineering-simulation-tool-adr/physics-engine',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Structural Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/structural-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Fluid dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/fluid-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Electromagnetics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/electromagnetics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: '3D-Design and Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/3d-design-and-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Multiphysics and system coupling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/multiphysics-and-system-coupling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Materials and data management',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/materials-and-data-management',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Integrated Geometry Modeling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/integrated-geometry-modeling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Interactive Topology Optimization',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/interactive-topology-optimization',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Real-time Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/real-time-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: '3D Electromagnetic Field Solver',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/3d-electromagnetic-field-solver',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Analysis of electric machines',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/analysis-of-electric-machines',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Electronics Reliability',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/electronics-reliability',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Low-Frequency Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/low-frequency-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Power & Signal Integrity',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/power-and-signal-integrity',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Turbulence Modeling',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/turbulence-modeling',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Combustion & Chemical Reactions',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/combustion-and-chemical-reactions',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Heat Transfer Conjugation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/heat-transfer-conjugation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'GPU Solver Acceleration',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/gpu-solver-acceleration',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Multiphase Flow Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/multiphase-flow-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Overset Mesh',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/overset-mesh',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Material Design',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/material-design',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Materials Data',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/materials-data',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Fluid-Structure Interaction',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/fluid-structure-interaction',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Thermal-Structural Simulations',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/thermal-structural-simulations',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Twin Builder',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/twin-builder',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Composite Structure Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/composite-structure-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Explicit Dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/explicit-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Fatigue Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/fatigue-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Fracture & Crack Simulation',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/fracture-and-crack-simulation',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Linear & Nonlinear Analysis',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/linear-and-nonlinear-analysis',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Rigid Dynamics',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/rigid-dynamics',
        date: 'April 2026',
        status: 'Draft',
    },
    {
        title: 'Topography & Shape Optimization',
        description: '',
        link: '/adrs/engineering-simulation-tool-adr/topography-and-shape-optimization',
        date: 'April 2026',
        status: 'Draft',
    },
];