'use client';
// import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';

import * as React from 'react';
import { styled, useTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import MuiAppBar, { AppBarProps as MuiAppBarProps } from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
// import Link from '@mui/material/Link';
import Link from 'next/link';
import { DrawerHeader } from './components/ResponsiveDrawer';
import ResponsiveDrawer from './components/ResponsiveDrawer';

// Select
import { usePathname } from 'next/navigation'

import "./globals.css";
import FormControl from "@mui/material/FormControl";
import InputLabel from "@mui/material/InputLabel";
import { Button, Grid, ListSubheader, MenuItem, Paper, Select, SelectChangeEvent } from "@mui/material";
import { useRouter } from 'next/navigation';
// import { AdrsList, NanoassemblyAdr, NanoassemblyAdrsList } from './adrs/nano-assembly-adr/nano-assembly-adrs-list';
import { InstantlyReusableLaunchpadAdrsList } from './adrs/instantly-reusable-launchpad-adr/instantly-reusable-launchpad-adrs-list';
import { StarshipNanoassemblyAdrsList } from './adrs/starship-nano-assembly-adr/starship-nano-assembly-adrs-list';
import ADRSelect from './components/ADRSelect';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const drawerWidth = 240;

interface AppBarProps extends MuiAppBarProps {
  open?: boolean;
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  // Router (for navigation and URL manipulation (select))
  const router = useRouter();

  // MUI
  const theme = useTheme();
  
  // Drawer
  const [open, setOpen] = React.useState(true);
  const handleDrawerOpen = () => {
    setOpen(true);
  };

  const Main = styled('main', { shouldForwardProp: (prop) => prop !== 'open' })<{
    open?: boolean;
  }>(({ theme, open }) => ({
    flexGrow: 1,
    padding: theme.spacing(3),

    // Mobile: always full width, never shifted
    marginLeft: 0,

    // Desktop base styles + original smooth variants
    [theme.breakpoints.up('sm')]: {
      marginLeft: `-${drawerWidth}px`,
      transition: theme.transitions.create('margin', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.leavingScreen,
      }),
    },

    variants: [
      {
        props: ({ open }) => open,
        style: {
          [theme.breakpoints.up('sm')]: {
            transition: theme.transitions.create('margin', {
              easing: theme.transitions.easing.easeOut,
              duration: theme.transitions.duration.enteringScreen,
            }),
            marginLeft: 0,
          },
        },
      },
    ],
  }));

  const AppBar = styled(MuiAppBar, {
    shouldForwardProp: (prop) => prop !== 'open',
  })<AppBarProps>(({ theme, open }) => ({
    transition: theme.transitions.create(['margin', 'width'], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.leavingScreen,
    }),

    // Desktop base styles
    [theme.breakpoints.up('sm')]: {
      ...(open
        ? {
            // When open → immediately apply the "entered" state
            width: `calc(100% - ${drawerWidth}px)`,
            marginLeft: `${drawerWidth}px`,
            transition: theme.transitions.create(['margin', 'width'], {
              easing: theme.transitions.easing.easeOut,
              duration: theme.transitions.duration.enteringScreen,
            }),
          }
        : {
            // When closed → keep the leaving transition
            width: '100%',
            marginLeft: 0,
          }),
    },

    variants: [
      {
        props: ({ open }) => open,
        style: {
          [theme.breakpoints.up('sm')]: {
            width: `calc(100% - ${drawerWidth}px)`,
            marginLeft: `${drawerWidth}px`,
            transition: theme.transitions.create(['margin', 'width'], {
              easing: theme.transitions.easing.easeOut,
              duration: theme.transitions.duration.enteringScreen,
            }),
          },
        },
      },
    ],
  }));

  // Add these (keep your existing `open` / `handleDrawerOpen` / `handleDrawerClose`)
  const [mobileOpen, setMobileOpen] = React.useState(false);
  const handleMobileDrawerToggle = () => {
    setMobileOpen((prev) => !prev);
  };
  const handleMobileDrawerClose = () => { setMobileOpen(false); };
  const handleDesktopDrawerClose = () => { setOpen(false); };
  
  return (
    <html lang="en" className={roboto.variable}>
      <body className="min-h-full flex flex-col">
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider
            options={{ key: 'css' }}
          >
            <Box sx={{ display: 'flex' }}>
              <CssBaseline />
              
              {/* <AppBar position="fixed" open={open}> */}
              <AppBar position="fixed" open={open}>
                <Toolbar>
                  {/* Mobile button — always visible on xs */}
                  <IconButton
                    color="inherit"
                    aria-label="open drawer"
                    onClick={handleMobileDrawerToggle}
                    edge="start"
                    sx={{ mr: 2, display: { xs: 'block', sm: 'none' } }}
                  >
                    <MenuIcon />
                  </IconButton>

                  {/* Desktop button — only visible when drawer is closed */}
                  <IconButton
                    color="inherit"
                    aria-label="open drawer"
                    onClick={handleDrawerOpen}
                    edge="start"
                    sx={{
                      mr: 2,
                      display: { xs: 'none', sm: open ? 'none' : 'block' },
                    }}
                  >
                    <MenuIcon />
                  </IconButton>
                  
                  <Box sx={{ flexGrow: 1 }}>
                    <Grid container spacing={3} alignItems="center">
                      <Grid size="grow">
                        <Typography variant="h6" noWrap component="div" sx={{ flexGrow: 1 }}>
                          <Link href="/" color="inherit">Architecture Decision Records</Link>
                        </Typography>
                      </Grid>

                      <Grid size={4}>
                        <ADRSelect />
                        
                        {/* <Box width={250} sx={{ marginRight: 20 }}>
                          
                        </Box> */}
                      </Grid>

                      <Grid size="grow">
                        <Typography variant="h6" noWrap component="div" align="right">
                          <Link 
                            href="https://rd-center.vercel.app/"
                            color="inherit"
                            target="_blank"
                          >
                            R&D Center
                          </Link>
                        </Typography>
                      </Grid>
                    </Grid>
                  </Box>
                  
                </Toolbar>
              </AppBar>

              <ResponsiveDrawer
                open={open}
                onDesktopDrawerClose={handleDesktopDrawerClose}
                mobileOpen={mobileOpen}
                onMobileDrawerClose={handleMobileDrawerClose}
              />

              {/* <Main open={open}> */}
              <Main open={open}>
                <DrawerHeader />
                {children}
              </Main>

            </Box>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
