import { AdrsList } from "@/app/[lang]/types/adr";

export const HealingAutismPerspectiveNeuralinkBCIsAdrsList: AdrsList = [
    {
        title: 'Precision mapping: AI-driven whole-brain connectomics to identify targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/precision-mapping-ai-driven-whole-brain-connectomics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Targeted intervention: Tools to add, remove, or modulate synapses without collateral damage',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/targeted-intervention-addition-removal-modulation-of-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Delivery and control: Non-invasive or minimally invasive methods to reach deep structures',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/delivery-and-control-non-invasive-methods-to-reach-deep-structures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Safety and reversibility: Ethical safeguards, as altering core neurology risks identity changes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/safety-and-reversibility-altering-core-neurology-and-identity-changes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Global rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/global-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AlphaFold for protein design & large-scale neural simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/alphafold-for-protein-design-&-large-scale-neural-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Billions of channels with nanomaterials & optogenetics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/billions-of-channels-with-nanomaterials-&-optogenetics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Synapse-level editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/synapse-level-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Gene Editing (e.g., CRISPR Variants) for Genetic Subtypes of Autism',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/gene-editing-for-genetic-subtypes-of-autism',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Normalization of synaptic formation/pruning during development or postnatally',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/normalization-of-synaptic-formation-or-pruning-during-development-or-postnatally',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Restoration of brain connectivity and seizure resilience with gene editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/restoration-of-brain-connectivity-and-seizure-resilience-with-gene-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Reduction of autism-like behaviors and seizures',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/reduction-of-autism-like-behaviors-and-seizures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Stem cells editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/stem-cells-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Protein quality control at synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/protein-quality-control-at-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-designed multiplex CRISPR systems to target multiple genes simultaneously',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-designed-multiplex-crispr-systems-to-target-multiple-genes-simultaneously',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Polygenic risk scores',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/polygenic-risk-scores',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Viral vectors for brain-wide delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/viral-vectors-for-brain-wide-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Rewriting synaptic densities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/rewriting-of-synaptic-densities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-optimized base/prime editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-optimized-base-prime-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Trillions of edits via self-replicating editors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/trillions-of-edits-via-self-replicating-editors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Self replicating editors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/self-replicating-editors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Real-time neural feedback loops',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/real-time-neural-feedback-loops',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Blood-brain barrier penetration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/blood-brain-barrier-penetration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Off-target effects',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/off-target-effects',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Brain-specific vectors & viability of postnatal edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/brain-specific-vectors-&-viability-of-postnatal-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Nanotechnology and Nanobots for Synapse Modification',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/nanotechnology-and-nanobots-for-synapse-modification',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Brain navigation with nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/brain-navigation-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Payload delivery to specific synapses with nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/payload-delivery-to-specific-synapses-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Plasticity modulation with nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/plasticity-modulation-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Strengthening/weakening connections via neurotransmitters or optogenetic switches',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/strengthening-weakening-connections-via-neurotransmitters-or-optogenetic-switches',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Magnetoelectric nanodiscs for wireless deep-brain stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/magnetoelectric-nanodiscs-for-wireless-deep-brain-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Activating neurons without implants',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/activating-neurons-without-implants',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Improvement of synaptic plasticity by reducing inflammation/oxidative stress with nanoparticles',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/improvement-of-synaptic-plasticity-by-reducing-inflammation-oxidative-stress-with-nanoparticles',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Integration of nanobots into neural circuits (for potential autism therapy)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/integration-of-nanobots-into-neural-circuits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Nano-neuro interfaces & maturation-dependent modulation in cultured neurons',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/nano-neuro-interfaces-&-maturation-dependent-modulation-in-cultured-neurons',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Parallel mapping & editing synapses with swarms of AI-controlled nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/parallel-mapping-&-editing-synapses-with-swarms-of-ai-controlled-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Swarms of AI-controlled nanobots (e.g., via quantum dots or DNA origami)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/swarms-of-ai-controlled-nanobots-quantum-dots-dna-origami',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Targeting DMN hubs through AI-algorithmic path optimization',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/targeting-dmn-hubs-through-ai-algorithmic-path-optimization',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Handling trillion-scale ops with self-assembling/replicating nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/handling-trillion-scale-ops-with-self-assembling-replicating-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'RNN-controlled nanobots for drug delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/rnn-controlled-nanobots-for-drug-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Behavior prediction with AI simulation (via large-scale brain models)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/behavior-prediction-with-ai-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Advanced BCIs and Neuromodulation for Network Rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/advanced-bcis-and-neuromodulation-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Reading & Writing signals with BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/reading-&-writing-signals-with-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI Simulation & enforcement of "neurotypical" patterns',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-simulation-&-enforcement-of-neurotypical-patterns',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Reversal of autism-like behaviors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/reversal-of-autism-like-behaviors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Chemogenetic control',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/chemogenetic-control',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Designer receptors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/designer-receptors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Sensory gatekeeping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/sensory-gatekeeping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Normalization of social/sensory responses (without synapse-level changes)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/normalization-of-social-sensory-responses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'TMS (transcranial magnetic stimulation)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/transcranial-magnetic-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: '(Evolved) High-density Neuralink implant arrays',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/high-density-neuralink-implant-arrays',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Channels via flexible nanowires',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/channels-via-flexible-nanowires',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Real-time fMRI/EEG data analysis with AI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/real-time-fmri-eeg-data-analysis-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Closed-loop stimulation to prune/strengthen synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/closed-loop-stimulation-to-prune-strengthen-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'LTP/LTD induction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ltp-ltd-induction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI brain mapping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-brain-mapping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Unified neuron reconstruction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/unified-neuron-reconstruction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Uploading corrected networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/uploading-corrected-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Non-invasive ultrasound or optogenetics for scale natwork rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/non-invasive-ultrasound-or-optogenetics-for-scale-natwork-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-Driven Hybrid Approaches',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-driven-hybrid-approaches',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Computational neuroscience',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/computational-neuroscience',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Modeling autism networks & edits prediction with AI orchestration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/modeling-autism-networks-&-edits-prediction-with-ai-orchestration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-neurotech policy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-neurotech-policy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Monitoring/manipulating brain activity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/monitoring-manipulating-brain-activity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Organoid models & edit testing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/organoid-models-&-edit-testing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Mapping, editing & verification with AI to address trillions by parallel processing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/mapping-editing-&-verification-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Combining CRISPR, nanobots, and BCIs in an AI loop',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/combining-crispr-nanobots-and-bcis-in-an-ai-loop',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Map with AI, edit with nano/gene tools, verify with BCI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/map-with-ai-edit-with-nano-gene-tools-verify-with-bci',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-brain interfaces',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-brain-interfaces',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Prototypes for targeted subtypes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/prototypes-for-targeted-subtypes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Full global rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/full-global-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum AI for simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-ai-for-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Self-healing nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/self-healing-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI automating hypothesis generation, simulation, experimentation, and iteration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-automating-hypothesis-generation-simulation-experimentation-and-iteration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Brain modeling',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/brain-modeling',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Precise brain simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/precise-brain-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Targeted rewiring for autism subtypes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/targeted-rewiring-for-autism-subtypes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Modulating synaptic connectivity in social/sensory networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/modulating-synaptic-connectivity-in-social-sensory-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-Orchestrated Convergent Tech Pipeline',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-orchestrated-convergent-tech-pipeline',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Parallel, AI-integrated pipeline fusing quantum simulation, gene/nanotech editing, and BCI validation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/fusing-quantum-simulation-gene-nanotech-editing-and-bci-validation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum-AI Brain Mapping and Simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-ai-brain-mapping-and-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Simulating complex quantum systems like neural dynamics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/simulating-complex-quantum-systems-like-neural-dynamics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Entanglement-like correlations in brain networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/entanglement-like-correlations-in-brain-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Modelling autisms global alterations at synapse-level fidelity & edits prediction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/modelling-autisms-global-alterations-at-synapse-level-fidelity-&-edits-prediction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Modelling default mode network disruptions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/modelling-default-mode-network-disruptions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Whole-brain connectomes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/whole-brain-connectomes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Simulation of whole-brain connectomes with AI & error-corrected quantum systems',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/simulation-of-whole-brain-connectomes-with-ai-&-error-corrected-quantum-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Generation of "digital twins" from genetic/fMRI data',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/generation-of-digital-twins-from-genetic-fmri-data',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Identifying trillions of synaptic targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/identifying-trillions-of-synaptic-targets',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Multiplex Gene Editing with AI-Optimized Delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/multiplex-gene-editing-with-ai-optimized-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Normalization of synaptic pruning',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/normalization of synaptic pruning',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Targeting autisms polygenic roots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/targeting-autisms-polygenic-roots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Prime/base editors for postnatal fixes, informed by quantum sims',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/prime-base-editors-for-postnatal-fixes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Brain-wide delivery with self-healing nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/brain-wide-delivery-with-self-healing-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'iPSC models (induced pluripotent stem cells)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ipsc-models-induced-pluripotent-stem-cells',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Testing in organoids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/testing-in-organoids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Automated safety predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/automated-safety-predictions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum optimization of molecular interactions for zero off-targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-optimization-of-molecular-interactions-for-zero-off-targets',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'High-Density BCI for Real-Time Modulation and Verification',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/high-density-bci-for-real-time-modulation-and-verification',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Wireless, biocompatible nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/wireless-biocompatible-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Evolved Neuralink implants to 10^6+ channels with wireless, biocompatible nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/evolved-neuralink-implants-with-wireless-biocompatible-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Use closed-loop AI to induce neuroplasticity (e.g., LTP/LTD to rewire networks), fine-tuning based on sim predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/use-closed-loop-ai-to-induce-neuroplasticity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Closed-loop AI for neuroplasticity induction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/closed-loop-ai-for-neuroplasticity-induction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'LTP/LTD for network rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ltp-ltd-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Fine-tuning based on sim predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/fine-tuning-based-on-sim-predictions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Real-time signal decoding/encoding with AI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/real-time-signal-decoding-encoding-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum-BCI hybrids for faster-than-classical processing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-bci-hybrids-for-faster-than-classical-processing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Non-invasive options (e.g., ultrasound neuromodulation)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/non-invasive-options-ultrasound-neuromodulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Prototypes for subtypes (e.g., sensory hyperexcitability) via chemogenetics like DREADDs, scaled AI-wide',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/prototypes-for-subtypes-via-chemogenetics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-simulated trials (validated by quantum accuracy) with neurodiversity input',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-simulated-trials-with-neurodiversity-input',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Predictive modeling for side effects prevention',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/predictive-modeling-for-side-effects-prevention',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum-AI sims for autism subtypes mapping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-ai-sims-for-autism-subtypes-mapping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Gene/nano prototypes in organoids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/gene-nano-prototypes-in-organoids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Human trials for targeted rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/human-trials-for-targeted-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Social cognition via prefrontal modulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/social-cognition-via-prefrontal-modulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Initial solutions for severe cases',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/initial-solutions-for-severe-cases',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Full-spectrum tools (global rewiring for mild-to-profound autism), deployable via clinics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/full-spectrum-global-rewiring-tools-deployable-via-clinics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum Sims & Nano delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-sims-&-nano-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Human-AI symbiosis to address unmet medical needs and enhance cognition',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/human-ai-symbiosis-to-address-unmet-medical-needs-and-enhance-cognition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Decoding speech from brain signals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decoding-speech-from-brain-signals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Restoring vision through "Blindsight" implants',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/restoring-vision-through-blindsight-implants',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Addressing psychiatric issues or pain',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/addressing-psychiatric-issues-or-pain',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Full-body control for paralyzed individuals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/full-body-control-for-paralyzed-individuals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Novel senses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/novel-senses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Novel senses like infrared vision',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/novel-senses-like-infrared-vision',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Safety through biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/safety-through-biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Safety through biocompatibility testing and robotic implantation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/safety-through-biocompatibility-testing-and-robotic-implantation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Procedures safer than routine surgeries',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/procedures-safer-than-routine-surgeries',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'BCIs enabling cognitive upgrades',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/bcis-enabling-cognitive-upgrades',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Instant knowledge access',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/instant-knowledge-access',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Memory recall on demand',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/memory-recall-on-demand',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Direct AI integration for faster thinking',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/direct-ai-integration-for-faster-thinking',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Memory enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/memory-enhancement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Sensory restoration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/sensory-restoration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Accessing deeper brain areas like the hippocampus',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/accessing-deeper-brain-areas-like-the-hippocampus',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Consensual telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/consensual-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Mind-controlled avatars in virtual worlds',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/mind-controlled-avatars-in-virtual-worlds',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Mind uploads',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/mind-uploads',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Abundance, eradicating diseases and fostering multi-planetary life',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/abundance-eradicating-diseases-and-fostering-multi-planetary-life',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Rapid scaling, tripling electrode counts and high-volume production',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/rapid-scaling-tripling-electrode-counts-and-high-volume-production',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Identity changes (e.g., altering personhood)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/identity-changes-altering-personhood',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Preclinical safety and ethical animal research',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/preclinical-safety-and-ethical-animal-research',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Long-term biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/long-term-biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Decoding accuracy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decoding-accuracy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Thread retraction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/thread-retraction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI surpassing human control via BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-surpassing-human-control-via-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Information overload or psychological distress',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/information-overload-or-psychological-distress',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Superhuman abilities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/superhuman-abilities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Ethical frameworks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ethical-frameworks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Restoring movement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/restoring-movement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Restoring vision',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/restoring-vision',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Whole-brain interface that achieves human-AI symbiosis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/whole-brain-interface-for-human-ai-symbiosis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Enhancement of cognitive capabilities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/enhancement-of-cognitive-capabilities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Exponential scaling in electrode density',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/exponential-scaling-in-electrode-density',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI integration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Mass-market devices for able-bodied users',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/mass-market-devices-for-able-bodied-users',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'High-density BCIs for network rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/high-density-bcis-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Quantum-AI simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/quantum-ai-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Symbiotic AI Integration BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/symbiotic-ai-integration-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Seamless human-AI synergy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/seamless-human-ai-synergy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'High-bandwidth (users) connections to computers or AI systems',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/high-bandwidth-users-connections-to-computers-or-ai-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Thought-based data exchange at speeds',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/thought-based-data-exchange-at-speeds',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'In the loop with superintelligence',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/in-the-loop-with-superintelligence',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Evolving from current signal decoding to full conceptual telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/from-signal-decoding-to-full-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Full conceptual telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/full-conceptual-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Direct sharing of uncompressed ideas between minds or with AI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/direct-sharing-of-uncompressed-ideas-between-minds-or-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Augmented social cognition',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/augmented-social-cognition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'AI-assisted neural pattern translation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/ai-assisted-neural-pattern-translation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Augmented social cognition via AI-assisted neural pattern translation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/augmented-social-cognition-via-ai-assisted-neural-pattern-translation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Cognitive Enhancement BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/cognitive-enhancement-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Memory augmentation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/memory-augmentation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Enablement of total recall',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/enablement-of-total-recall',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Implants targeting regions like the hippocampus for memory augmentation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/implants-for-memory-augmentation',
        date: 'March 2026',
        status: 'Draft',
    },
    // {
    //     title: 'Instant knowledge access',
    //     description: '',
    //     link: '/adrs/instant-knowledge-access'
    // },
    {
        title: 'Memory uploads/downloads',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/memory-uploads-downloads',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Network rewiring, AI-optimized stimulation to address neurodevelopmental differences like autism by dynamically modulating connectivity in real-time',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/network-rewiring-ai-optimized-stimulation-to-address-neurodevelopmental-differences',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Sensory Augmentation BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/sensory-augmentation-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Restoring and enhancing senses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/restoring-and-enhancing-senses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Infrared, ultraviolet, or radar vision through cortical stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/infrared-ultraviolet-or-radar-vision-through-cortical-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    // {
    //     title: 'Novel senses',
    //     description: '',
    //     link: '/adrs/novel-senses'
    // },
    {
        title: 'Magnetic field detection',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/magnetic-field-detection',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Direct data visualization',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/direct-data-visualization',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Nanotech/BCI hybrids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/nanotech-bci-hybrids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Global sensory network edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/global-sensory-network-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Nanotech/BCI hybrids for global sensory network edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/nanotech-bci-hybrids-for-global-sensory-network-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Aiding sensory processing in autism spectra',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/aiding-sensory-processing-in-autism-spectra',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Whole-Brain Interface BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/whole-brain-interface-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Generalized input/output system interfacing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/generalized-input-output-system-interfacing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Generalized input/output system interfacing with "every aspect of the brain',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/generalized-input-output-system-interfacing-with-every-aspect-of-the-brain',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Bidirectional control over thoughts, emotions, and actions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/bidirectional-control-over-thoughts-emotions-and-actions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Mind-controlled environments',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/mind-controlled-environments',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Virtual reality immersion without peripherals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/virtual-reality-immersion-without-peripherals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Collective intelligence networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/collective-intelligence-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Trillion-synapse editing via AI loops',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/trillion-synapse-editing-via-ai-loops',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Reversible "rewiring" for conditions like autism without erasing neurodiversity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/reversible-rewiring-without-erasing-neurodiversity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Therapeutic-Enhancement Hybrid BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/therapeutic-enhancement-hybrid-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Treating paralysis, blindness, or psychiatric conditions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/treating-paralysis-blindness-or-psychiatric-conditions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Elective upgrades',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/elective-upgrades',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'New dimensions of human potential',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/new-dimensions-of-human potential',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Restoring autonomy while unlocking new dimensions of human potential',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/restoring-autonomy-while-unlocking-new-dimensions-of-human-potential',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'High-volume production',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/high-volume-production',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Subtype-specific modulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/subtype-specific-modulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Calming hyperexcitable networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/calming-hyperexcitable-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Transitioning from support to optional enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/transitioning-from-support-to-optional-enhancement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        title: 'Subtype-specific modulation for autism (calming hyperexcitable networks), from support to optional enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/subtype-specific-modulation-for-autism',
        date: 'March 2026',
        status: 'Draft',
    },
];