import { AdrsList } from "@/app/[lang]/types/adr";

export const HealingAutismPerspectiveNeuralinkBCIsAdrsList: AdrsList = [
    {
        translationKey: 'Precision mapping: AI-driven whole-brain connectomics to identify targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/precision-mapping-ai-driven-whole-brain-connectomics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Targeted intervention: Tools to add, remove, or modulate synapses without collateral damage',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeted-intervention-addition-removal-modulation-of-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Delivery and control: Non-invasive or minimally invasive methods to reach deep structures',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/delivery-and-control-non-invasive-methods-to-reach-deep-structures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Safety and reversibility: Ethical safeguards, as altering core neurology risks identity changes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/safety-and-reversibility-altering-core-neurology-and-identity-changes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Global rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/global-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AlphaFold for protein design & large-scale neural simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/alphafold-for-protein-design-&-large-scale-neural-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Billions of channels with nanomaterials & optogenetics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/billions-of-channels-with-nanomaterials-&-optogenetics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Synapse-level editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/synapse-level-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Gene Editing (e.g., CRISPR Variants) for Genetic Subtypes of Autism',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/gene-editing-for-genetic-subtypes-of-autism',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Normalization of synaptic formation/pruning during development or postnatally',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/normalization-of-synaptic-formation-or-pruning-during-development-or-postnatally',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Restoration of brain connectivity and seizure resilience with gene editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoration-of-brain-connectivity-and-seizure-resilience-with-gene-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Reduction of autism-like behaviors and seizures',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reduction-of-autism-like-behaviors-and-seizures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Stem cells editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/stem-cells-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Protein quality control at synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/protein-quality-control-at-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-designed multiplex CRISPR systems to target multiple genes simultaneously',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-designed-multiplex-crispr-systems-to-target-multiple-genes-simultaneously',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Polygenic risk scores',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/polygenic-risk-scores',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Viral vectors for brain-wide delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/viral-vectors-for-brain-wide-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Rewriting synaptic densities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/rewriting-of-synaptic-densities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-optimized base/prime editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-optimized-base-prime-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Trillions of edits via self-replicating editors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/trillions-of-edits-via-self-replicating-editors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Self replicating editors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/self-replicating-editors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Real-time neural feedback loops',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/real-time-neural-feedback-loops',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Blood-brain barrier penetration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/blood-brain-barrier-penetration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Off-target effects',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/off-target-effects',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Brain-specific vectors & viability of postnatal edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-specific-vectors-&-viability-of-postnatal-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanotechnology and Nanobots for Synapse Modification',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nanotechnology-and-nanobots-for-synapse-modification',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Brain navigation with nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-navigation-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Payload delivery to specific synapses with nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/payload-delivery-to-specific-synapses-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Plasticity modulation with nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/plasticity-modulation-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Strengthening/weakening connections via neurotransmitters or optogenetic switches',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/strengthening-weakening-connections-via-neurotransmitters-or-optogenetic-switches',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Magnetoelectric nanodiscs for wireless deep-brain stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/magnetoelectric-nanodiscs-for-wireless-deep-brain-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Activating neurons without implants',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/activating-neurons-without-implants',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Improvement of synaptic plasticity by reducing inflammation/oxidative stress with nanoparticles',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/improvement-of-synaptic-plasticity-by-reducing-inflammation-oxidative-stress-with-nanoparticles',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Integration of nanobots into neural circuits (for potential autism therapy)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/integration-of-nanobots-into-neural-circuits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nano-neuro interfaces & maturation-dependent modulation in cultured neurons',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nano-neuro-interfaces-&-maturation-dependent-modulation-in-cultured-neurons',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Parallel mapping & editing synapses with swarms of AI-controlled nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/parallel-mapping-&-editing-synapses-with-swarms-of-ai-controlled-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Swarms of AI-controlled nanobots (e.g., via quantum dots or DNA origami)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/swarms-of-ai-controlled-nanobots-quantum-dots-dna-origami',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Targeting DMN hubs through AI-algorithmic path optimization',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeting-dmn-hubs-through-ai-algorithmic-path-optimization',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Handling trillion-scale ops with self-assembling/replicating nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/handling-trillion-scale-ops-with-self-assembling-replicating-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'RNN-controlled nanobots for drug delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/rnn-controlled-nanobots-for-drug-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Behavior prediction with AI simulation (via large-scale brain models)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/behavior-prediction-with-ai-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Advanced BCIs and Neuromodulation for Network Rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/advanced-bcis-and-neuromodulation-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Reading & Writing signals with BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reading-&-writing-signals-with-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI Simulation & enforcement of "neurotypical" patterns',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-simulation-&-enforcement-of-neurotypical-patterns',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Reversal of autism-like behaviors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reversal-of-autism-like-behaviors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Chemogenetic control',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/chemogenetic-control',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Designer receptors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/designer-receptors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensory gatekeeping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/sensory-gatekeeping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Normalization of social/sensory responses (without synapse-level changes)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/normalization-of-social-sensory-responses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'TMS (transcranial magnetic stimulation)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/transcranial-magnetic-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: '(Evolved) High-density Neuralink implant arrays',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-density-neuralink-implant-arrays',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Channels via flexible nanowires',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/channels-via-flexible-nanowires',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Real-time fMRI/EEG data analysis with AI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/real-time-fmri-eeg-data-analysis-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Closed-loop stimulation to prune/strengthen synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/closed-loop-stimulation-to-prune-strengthen-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'LTP/LTD induction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ltp-ltd-induction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI brain mapping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-brain-mapping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Unified neuron reconstruction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/unified-neuron-reconstruction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Uploading corrected networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/uploading-corrected-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Non-invasive ultrasound or optogenetics for scale natwork rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/non-invasive-ultrasound-or-optogenetics-for-scale-natwork-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-Driven Hybrid Approaches',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-driven-hybrid-approaches',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Computational neuroscience',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/computational-neuroscience',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Modeling autism networks & edits prediction with AI orchestration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modeling-autism-networks-&-edits-prediction-with-ai-orchestration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-neurotech policy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-neurotech-policy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Monitoring/manipulating brain activity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/monitoring-manipulating-brain-activity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Organoid models & edit testing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/organoid-models-&-edit-testing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Mapping, editing & verification with AI to address trillions by parallel processing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mapping-editing-&-verification-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Combining CRISPR, nanobots, and BCIs in an AI loop',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/combining-crispr-nanobots-and-bcis-in-an-ai-loop',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Map with AI, edit with nano/gene tools, verify with BCI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/map-with-ai-edit-with-nano-gene-tools-verify-with-bci',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-brain interfaces',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-brain-interfaces',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Prototypes for targeted subtypes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/prototypes-for-targeted-subtypes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full global rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-global-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum AI for simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-for-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Self-healing nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/self-healing-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI automating hypothesis generation, simulation, experimentation, and iteration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-automating-hypothesis-generation-simulation-experimentation-and-iteration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Brain modeling',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-modeling',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Precise brain simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/precise-brain-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Targeted rewiring for autism subtypes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeted-rewiring-for-autism-subtypes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Modulating synaptic connectivity in social/sensory networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modulating-synaptic-connectivity-in-social-sensory-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-Orchestrated Convergent Tech Pipeline',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-orchestrated-convergent-tech-pipeline',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Parallel, AI-integrated pipeline fusing quantum simulation, gene/nanotech editing, and BCI validation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/fusing-quantum-simulation-gene-nanotech-editing-and-bci-validation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum-AI Brain Mapping and Simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-brain-mapping-and-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Simulating complex quantum systems like neural dynamics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/simulating-complex-quantum-systems-like-neural-dynamics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Entanglement-like correlations in brain networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/entanglement-like-correlations-in-brain-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Modelling autisms global alterations at synapse-level fidelity & edits prediction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modelling-autisms-global-alterations-at-synapse-level-fidelity-&-edits-prediction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Modelling default mode network disruptions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modelling-default-mode-network-disruptions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Whole-brain connectomes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/whole-brain-connectomes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Simulation of whole-brain connectomes with AI & error-corrected quantum systems',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/simulation-of-whole-brain-connectomes-with-ai-&-error-corrected-quantum-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Generation of "digital twins" from genetic/fMRI data',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/generation-of-digital-twins-from-genetic-fmri-data',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Identifying trillions of synaptic targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/identifying-trillions-of-synaptic-targets',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Multiplex Gene Editing with AI-Optimized Delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/multiplex-gene-editing-with-ai-optimized-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Normalization of synaptic pruning',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/normalization-of-synaptic-pruning',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Targeting autisms polygenic roots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeting-autisms-polygenic-roots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Prime/base editors for postnatal fixes, informed by quantum sims',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/prime-base-editors-for-postnatal-fixes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Brain-wide delivery with self-healing nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-wide-delivery-with-self-healing-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'iPSC models (induced pluripotent stem cells)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ipsc-models-induced-pluripotent-stem-cells',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Testing in organoids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/testing-in-organoids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Automated safety predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/automated-safety-predictions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum optimization of molecular interactions for zero off-targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-optimization-of-molecular-interactions-for-zero-off-targets',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'High-Density BCI for Real-Time Modulation and Verification',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-density-bci-for-real-time-modulation-and-verification',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Wireless, biocompatible nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/wireless-biocompatible-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Evolved Neuralink implants to 10^6+ channels with wireless, biocompatible nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/evolved-neuralink-implants-with-wireless-biocompatible-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Use closed-loop AI to induce neuroplasticity (e.g., LTP/LTD to rewire networks), fine-tuning based on sim predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/use-closed-loop-ai-to-induce-neuroplasticity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Closed-loop AI for neuroplasticity induction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/closed-loop-ai-for-neuroplasticity-induction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'LTP/LTD for network rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ltp-ltd-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Fine-tuning based on sim predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/fine-tuning-based-on-sim-predictions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Real-time signal decoding/encoding with AI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/real-time-signal-decoding-encoding-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum-BCI hybrids for faster-than-classical processing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-bci-hybrids-for-faster-than-classical-processing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Non-invasive options (e.g., ultrasound neuromodulation)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/non-invasive-options-ultrasound-neuromodulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Prototypes for subtypes (e.g., sensory hyperexcitability) via chemogenetics like DREADDs, scaled AI-wide',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/prototypes-for-subtypes-via-chemogenetics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-simulated trials (validated by quantum accuracy) with neurodiversity input',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-simulated-trials-with-neurodiversity-input',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Predictive modeling for side effects prevention',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/predictive-modeling-for-side-effects-prevention',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum-AI sims for autism subtypes mapping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-sims-for-autism-subtypes-mapping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Gene/nano prototypes in organoids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/gene-nano-prototypes-in-organoids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Human trials for targeted rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/human-trials-for-targeted-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Social cognition via prefrontal modulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/social-cognition-via-prefrontal-modulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Initial solutions for severe cases',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/initial-solutions-for-severe-cases',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full-spectrum tools (global rewiring for mild-to-profound autism), deployable via clinics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-spectrum-global-rewiring-tools-deployable-via-clinics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum Sims & Nano delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-sims-&-nano-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Human-AI symbiosis to address unmet medical needs and enhance cognition',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/human-ai-symbiosis-to-address-unmet-medical-needs-and-enhance-cognition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Decoding speech from brain signals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/decoding-speech-from-brain-signals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Restoring vision through "Blindsight" implants',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-vision-through-blindsight-implants',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Addressing psychiatric issues or pain',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/addressing-psychiatric-issues-or-pain',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full-body control for paralyzed individuals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-body-control-for-paralyzed-individuals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Novel senses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/novel-senses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Novel senses like infrared vision',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/novel-senses-like-infrared-vision',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Safety through biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/safety-through-biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Safety through biocompatibility testing and robotic implantation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/safety-through-biocompatibility-testing-and-robotic-implantation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Procedures safer than routine surgeries',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/procedures-safer-than-routine-surgeries',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'BCIs enabling cognitive upgrades',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/bcis-enabling-cognitive-upgrades',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Instant knowledge access',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/instant-knowledge-access',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Memory recall on demand',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-recall-on-demand',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Direct AI integration for faster thinking',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/direct-ai-integration-for-faster-thinking',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Memory enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-enhancement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensory restoration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/sensory-restoration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Accessing deeper brain areas like the hippocampus',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/accessing-deeper-brain-areas-like-the-hippocampus',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Consensual telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/consensual-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Mind-controlled avatars in virtual worlds',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mind-controlled-avatars-in-virtual-worlds',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Mind uploads',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mind-uploads',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Abundance, eradicating diseases and fostering multi-planetary life',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/abundance-eradicating-diseases-and-fostering-multi-planetary-life',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Rapid scaling, tripling electrode counts and high-volume production',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/rapid-scaling-tripling-electrode-counts-and-high-volume-production',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Identity changes (e.g., altering personhood)',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/identity-changes-altering-personhood',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Preclinical safety and ethical animal research',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/preclinical-safety-and-ethical-animal-research',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Long-term biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/long-term-biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Decoding accuracy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/decoding-accuracy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Thread retraction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/thread-retraction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI surpassing human control via BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-surpassing-human-control-via-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Information overload or psychological distress',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/information-overload-or-psychological-distress',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Superhuman abilities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/superhuman-abilities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Ethical frameworks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ethical-frameworks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Restoring movement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-movement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Restoring vision',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-vision',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Whole-brain interface that achieves human-AI symbiosis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/whole-brain-interface-for-human-ai-symbiosis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Enhancement of cognitive capabilities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/enhancement-of-cognitive-capabilities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Exponential scaling in electrode density',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/exponential-scaling-in-electrode-density',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI integration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Mass-market devices for able-bodied users',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mass-market-devices-for-able-bodied-users',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'High-density BCIs for network rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-density-bcis-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Quantum-AI simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Symbiotic AI Integration BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/symbiotic-ai-integration-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Seamless human-AI synergy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/seamless-human-ai-synergy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'High-bandwidth (users) connections to computers or AI systems',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-bandwidth-users-connections-to-computers-or-ai-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Thought-based data exchange at speeds',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/thought-based-data-exchange-at-speeds',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'In the loop with superintelligence',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/in-the-loop-with-superintelligence',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Evolving from current signal decoding to full conceptual telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/from-signal-decoding-to-full-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Full conceptual telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-conceptual-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Direct sharing of uncompressed ideas between minds or with AI',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/direct-sharing-of-uncompressed-ideas-between-minds-or-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Augmented social cognition',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/augmented-social-cognition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'AI-assisted neural pattern translation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-assisted-neural-pattern-translation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Augmented social cognition via AI-assisted neural pattern translation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/augmented-social-cognition-via-ai-assisted-neural-pattern-translation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Cognitive Enhancement BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/cognitive-enhancement-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Memory augmentation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-augmentation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Enablement of total recall',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/enablement-of-total-recall',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Implants targeting regions like the hippocampus for memory augmentation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/implants-for-memory-augmentation',
        date: 'March 2026',
        status: 'Draft',
    },
    // {
    //     translationKey: 'Instant knowledge access',
    //     description: '',
    //     link: '/adrs/instant-knowledge-access'
    // },
    {
        translationKey: 'Memory uploads/downloads',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-uploads-downloads',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Network rewiring, AI-optimized stimulation to address neurodevelopmental differences like autism by dynamically modulating connectivity in real-time',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/network-rewiring-ai-optimized-stimulation-to-address-neurodevelopmental-differences',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Sensory Augmentation BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/sensory-augmentation-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Restoring and enhancing senses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-and-enhancing-senses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Infrared, ultraviolet, or radar vision through cortical stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/infrared-ultraviolet-or-radar-vision-through-cortical-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    // {
    //     translationKey: 'Novel senses',
    //     description: '',
    //     link: '/adrs/novel-senses'
    // },
    {
        translationKey: 'Magnetic field detection',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/magnetic-field-detection',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Direct data visualization',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/direct-data-visualization',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanotech/BCI hybrids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nanotech-bci-hybrids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Global sensory network edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/global-sensory-network-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Nanotech/BCI hybrids for global sensory network edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nanotech-bci-hybrids-for-global-sensory-network-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Aiding sensory processing in autism spectra',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/aiding-sensory-processing-in-autism-spectra',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Whole-Brain Interface BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/whole-brain-interface-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Generalized input/output system interfacing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/generalized-input-output-system-interfacing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Generalized input/output system interfacing with "every aspect of the brain',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/generalized-input-output-system-interfacing-with-every-aspect-of-the-brain',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Bidirectional control over thoughts, emotions, and actions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/bidirectional-control-over-thoughts-emotions-and-actions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Mind-controlled environments',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mind-controlled-environments',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Virtual reality immersion without peripherals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/virtual-reality-immersion-without-peripherals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Collective intelligence networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/collective-intelligence-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Trillion-synapse editing via AI loops',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/trillion-synapse-editing-via-ai-loops',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Reversible "rewiring" for conditions like autism without erasing neurodiversity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reversible-rewiring-without-erasing-neurodiversity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Therapeutic-Enhancement Hybrid BCIs',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/therapeutic-enhancement-hybrid-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Treating paralysis, blindness, or psychiatric conditions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/treating-paralysis-blindness-or-psychiatric-conditions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Elective upgrades',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/elective-upgrades',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'New dimensions of human potential',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/new-dimensions-of-human-potential',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Restoring autonomy while unlocking new dimensions of human potential',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-autonomy-while-unlocking-new-dimensions-of-human-potential',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'High-volume production',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-volume-production',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Subtype-specific modulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/subtype-specific-modulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Calming hyperexcitable networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/calming-hyperexcitable-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Transitioning from support to optional enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/transitioning-from-support-to-optional-enhancement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'Subtype-specific modulation for autism (calming hyperexcitable networks), from support to optional enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/subtype-specific-modulation-for-autism',
        date: 'March 2026',
        status: 'Draft',
    },
];