import { AdrsList } from "@/app/[lang]/types/adr";

export const HealingAutismPerspectiveNeuralinkBCIsAdrsList: AdrsList = [
    {
        translationKey: 'precision-mapping-ai-driven-whole-brain-connectomics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/precision-mapping-ai-driven-whole-brain-connectomics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'targeted-intervention-addition-removal-modulation-of-synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeted-intervention-addition-removal-modulation-of-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'delivery-and-control-non-invasive-methods-to-reach-deep-structures',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/delivery-and-control-non-invasive-methods-to-reach-deep-structures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'safety-and-reversibility-altering-core-neurology-and-identity-changes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/safety-and-reversibility-altering-core-neurology-and-identity-changes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'global-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/global-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'alphafold-for-protein-design-&-large-scale-neural-simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/alphafold-for-protein-design-&-large-scale-neural-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'billions-of-channels-with-nanomaterials-&-optogenetics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/billions-of-channels-with-nanomaterials-&-optogenetics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'synapse-level-editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/synapse-level-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'gene-editing-for-genetic-subtypes-of-autism',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/gene-editing-for-genetic-subtypes-of-autism',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'normalization-of-synaptic-formation-or-pruning-during-development-or-postnatally',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/normalization-of-synaptic-formation-or-pruning-during-development-or-postnatally',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'restoration-of-brain-connectivity-and-seizure-resilience-with-gene-editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoration-of-brain-connectivity-and-seizure-resilience-with-gene-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'reduction-of-autism-like-behaviors-and-seizures',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reduction-of-autism-like-behaviors-and-seizures',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'stem-cells-editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/stem-cells-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'protein-quality-control-at-synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/protein-quality-control-at-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-designed-multiplex-crispr-systems-to-target-multiple-genes-simultaneously',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-designed-multiplex-crispr-systems-to-target-multiple-genes-simultaneously',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'polygenic-risk-scores',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/polygenic-risk-scores',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'viral-vectors-for-brain-wide-delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/viral-vectors-for-brain-wide-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'rewriting-of-synaptic-densities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/rewriting-of-synaptic-densities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-optimized-base-prime-editing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-optimized-base-prime-editing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'trillions-of-edits-via-self-replicating-editors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/trillions-of-edits-via-self-replicating-editors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'self-replicating-editors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/self-replicating-editors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'real-time-neural-feedback-loops',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/real-time-neural-feedback-loops',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'blood-brain-barrier-penetration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/blood-brain-barrier-penetration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'off-target-effects',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/off-target-effects',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'brain-specific-vectors-&-viability-of-postnatal-edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-specific-vectors-&-viability-of-postnatal-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanotechnology-and-nanobots-for-synapse-modification',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nanotechnology-and-nanobots-for-synapse-modification',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'brain-navigation-with-nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-navigation-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'payload-delivery-to-specific-synapses-with-nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/payload-delivery-to-specific-synapses-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'plasticity-modulation-with-nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/plasticity-modulation-with-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'strengthening-weakening-connections-via-neurotransmitters-or-optogenetic-switches',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/strengthening-weakening-connections-via-neurotransmitters-or-optogenetic-switches',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'magnetoelectric-nanodiscs-for-wireless-deep-brain-stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/magnetoelectric-nanodiscs-for-wireless-deep-brain-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'activating-neurons-without-implants',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/activating-neurons-without-implants',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'improvement-of-synaptic-plasticity-by-reducing-inflammation-oxidative-stress-with-nanoparticles',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/improvement-of-synaptic-plasticity-by-reducing-inflammation-oxidative-stress-with-nanoparticles',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'integration-of-nanobots-into-neural-circuits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/integration-of-nanobots-into-neural-circuits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nano-neuro-interfaces-&-maturation-dependent-modulation-in-cultured-neurons',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nano-neuro-interfaces-&-maturation-dependent-modulation-in-cultured-neurons',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'parallel-mapping-&-editing-synapses-with-swarms-of-ai-controlled-nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/parallel-mapping-&-editing-synapses-with-swarms-of-ai-controlled-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'swarms-of-ai-controlled-nanobots-quantum-dots-dna-origami',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/swarms-of-ai-controlled-nanobots-quantum-dots-dna-origami',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'targeting-dmn-hubs-through-ai-algorithmic-path-optimization',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeting-dmn-hubs-through-ai-algorithmic-path-optimization',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'handling-trillion-scale-ops-with-self-assembling-replicating-nanobots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/handling-trillion-scale-ops-with-self-assembling-replicating-nanobots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'rnn-controlled-nanobots-for-drug-delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/rnn-controlled-nanobots-for-drug-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'behavior-prediction-with-ai-simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/behavior-prediction-with-ai-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'advanced-bcis-and-neuromodulation-for-network-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/advanced-bcis-and-neuromodulation-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'reading-&-writing-signals-with-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reading-&-writing-signals-with-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-simulation-&-enforcement-of-neurotypical-patterns',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-simulation-&-enforcement-of-neurotypical-patterns',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'reversal-of-autism-like-behaviors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reversal-of-autism-like-behaviors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'chemogenetic-control',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/chemogenetic-control',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'designer-receptors',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/designer-receptors',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensory-gatekeeping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/sensory-gatekeeping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'normalization-of-social-sensory-responses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/normalization-of-social-sensory-responses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'transcranial-magnetic-stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/transcranial-magnetic-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-density-neuralink-implant-arrays',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-density-neuralink-implant-arrays',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'channels-via-flexible-nanowires',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/channels-via-flexible-nanowires',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'real-time-fmri-eeg-data-analysis-with-ai',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/real-time-fmri-eeg-data-analysis-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'closed-loop-stimulation-to-prune-strengthen-synapses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/closed-loop-stimulation-to-prune-strengthen-synapses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ltp-ltd-induction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ltp-ltd-induction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-brain-mapping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-brain-mapping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'unified-neuron-reconstruction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/unified-neuron-reconstruction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'uploading-corrected-networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/uploading-corrected-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'non-invasive-ultrasound-or-optogenetics-for-scale-natwork-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/non-invasive-ultrasound-or-optogenetics-for-scale-natwork-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-driven-hybrid-approaches',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-driven-hybrid-approaches',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'computational-neuroscience',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/computational-neuroscience',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'modeling-autism-networks-&-edits-prediction-with-ai-orchestration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modeling-autism-networks-&-edits-prediction-with-ai-orchestration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-neurotech-policy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-neurotech-policy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'monitoring-manipulating-brain-activity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/monitoring-manipulating-brain-activity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'organoid-models-&-edit-testing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/organoid-models-&-edit-testing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'mapping-editing-&-verification-with-ai',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mapping-editing-&-verification-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'combining-crispr-nanobots-and-bcis-in-an-ai-loop',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/combining-crispr-nanobots-and-bcis-in-an-ai-loop',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'map-with-ai-edit-with-nano-gene-tools-verify-with-bci',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/map-with-ai-edit-with-nano-gene-tools-verify-with-bci',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-brain-interfaces',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-brain-interfaces',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'prototypes-for-targeted-subtypes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/prototypes-for-targeted-subtypes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-global-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-global-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-ai-for-simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-for-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'self-healing-nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/self-healing-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-automating-hypothesis-generation-simulation-experimentation-and-iteration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-automating-hypothesis-generation-simulation-experimentation-and-iteration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'brain-modeling',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-modeling',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'precise-brain-simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/precise-brain-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'targeted-rewiring-for-autism-subtypes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeted-rewiring-for-autism-subtypes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'modulating-synaptic-connectivity-in-social-sensory-networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modulating-synaptic-connectivity-in-social-sensory-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-orchestrated-convergent-tech-pipeline',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-orchestrated-convergent-tech-pipeline',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fusing-quantum-simulation-gene-nanotech-editing-and-bci-validation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/fusing-quantum-simulation-gene-nanotech-editing-and-bci-validation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-ai-brain-mapping-and-simulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-brain-mapping-and-simulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'simulating-complex-quantum-systems-like-neural-dynamics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/simulating-complex-quantum-systems-like-neural-dynamics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'entanglement-like-correlations-in-brain-networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/entanglement-like-correlations-in-brain-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'modelling-autisms-global-alterations-at-synapse-level-fidelity-&-edits-prediction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modelling-autisms-global-alterations-at-synapse-level-fidelity-&-edits-prediction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'modelling-default-mode-network-disruptions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/modelling-default-mode-network-disruptions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'whole-brain-connectomes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/whole-brain-connectomes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'simulation-of-whole-brain-connectomes-with-ai-&-error-corrected-quantum-systems',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/simulation-of-whole-brain-connectomes-with-ai-&-error-corrected-quantum-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'generation-of-digital-twins-from-genetic-fmri-data',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/generation-of-digital-twins-from-genetic-fmri-data',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'identifying-trillions-of-synaptic-targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/identifying-trillions-of-synaptic-targets',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'multiplex-gene-editing-with-ai-optimized-delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/multiplex-gene-editing-with-ai-optimized-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'normalization of synaptic pruning',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/normalization-of-synaptic-pruning',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'targeting-autisms-polygenic-roots',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/targeting-autisms-polygenic-roots',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'prime-base-editors-for-postnatal-fixes',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/prime-base-editors-for-postnatal-fixes',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'brain-wide-delivery-with-self-healing-nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/brain-wide-delivery-with-self-healing-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ipsc-models-induced-pluripotent-stem-cells',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ipsc-models-induced-pluripotent-stem-cells',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'testing-in-organoids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/testing-in-organoids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'automated-safety-predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/automated-safety-predictions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-optimization-of-molecular-interactions-for-zero-off-targets',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-optimization-of-molecular-interactions-for-zero-off-targets',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-density-bci-for-real-time-modulation-and-verification',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-density-bci-for-real-time-modulation-and-verification',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'wireless-biocompatible-nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/wireless-biocompatible-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'evolved-neuralink-implants-with-wireless-biocompatible-nanomaterials',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/evolved-neuralink-implants-with-wireless-biocompatible-nanomaterials',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'use-closed-loop-ai-to-induce-neuroplasticity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/use-closed-loop-ai-to-induce-neuroplasticity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'closed-loop-ai-for-neuroplasticity-induction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/closed-loop-ai-for-neuroplasticity-induction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ltp-ltd-for-network-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ltp-ltd-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'fine-tuning-based-on-sim-predictions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/fine-tuning-based-on-sim-predictions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'real-time-signal-decoding-encoding-with-ai',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/real-time-signal-decoding-encoding-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-bci-hybrids-for-faster-than-classical-processing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-bci-hybrids-for-faster-than-classical-processing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'non-invasive-options-ultrasound-neuromodulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/non-invasive-options-ultrasound-neuromodulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'prototypes-for-subtypes-via-chemogenetics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/prototypes-for-subtypes-via-chemogenetics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-simulated-trials-with-neurodiversity-input',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-simulated-trials-with-neurodiversity-input',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'predictive-modeling-for-side-effects-prevention',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/predictive-modeling-for-side-effects-prevention',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-ai-sims-for-autism-subtypes-mapping',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-sims-for-autism-subtypes-mapping',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'gene-nano-prototypes-in-organoids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/gene-nano-prototypes-in-organoids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'human-trials-for-targeted-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/human-trials-for-targeted-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'social-cognition-via-prefrontal-modulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/social-cognition-via-prefrontal-modulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'initial-solutions-for-severe-cases',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/initial-solutions-for-severe-cases',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-spectrum-global-rewiring-tools-deployable-via-clinics',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-spectrum-global-rewiring-tools-deployable-via-clinics',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-sims-&-nano-delivery',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-sims-&-nano-delivery',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'human-ai-symbiosis-to-address-unmet-medical-needs-and-enhance-cognition',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/human-ai-symbiosis-to-address-unmet-medical-needs-and-enhance-cognition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'decoding-speech-from-brain-signals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/decoding-speech-from-brain-signals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'restoring-vision-through-blindsight-implants',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-vision-through-blindsight-implants',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'addressing-psychiatric-issues-or-pain',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/addressing-psychiatric-issues-or-pain',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-body-control-for-paralyzed-individuals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-body-control-for-paralyzed-individuals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'novel-senses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/novel-senses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'novel-senses-like-infrared-vision',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/novel-senses-like-infrared-vision',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'safety-through-biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/safety-through-biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'safety-through-biocompatibility-testing-and-robotic-implantation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/safety-through-biocompatibility-testing-and-robotic-implantation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'procedures-safer-than-routine-surgeries',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/procedures-safer-than-routine-surgeries',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'bcis-enabling-cognitive-upgrades',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/bcis-enabling-cognitive-upgrades',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'memory-recall-on-demand',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-recall-on-demand',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'direct-ai-integration-for-faster-thinking',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/direct-ai-integration-for-faster-thinking',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'memory-enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-enhancement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensory-restoration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/sensory-restoration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'accessing-deeper-brain-areas-like-the-hippocampus',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/accessing-deeper-brain-areas-like-the-hippocampus',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'consensual-telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/consensual-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'mind-controlled-avatars-in-virtual-worlds',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mind-controlled-avatars-in-virtual-worlds',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'mind-uploads',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mind-uploads',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'abundance-eradicating-diseases-and-fostering-multi-planetary-life',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/abundance-eradicating-diseases-and-fostering-multi-planetary-life',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'rapid-scaling-tripling-electrode-counts-and-high-volume-production',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/rapid-scaling-tripling-electrode-counts-and-high-volume-production',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'identity-changes-altering-personhood',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/identity-changes-altering-personhood',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'preclinical-safety-and-ethical-animal-research',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/preclinical-safety-and-ethical-animal-research',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'long-term-biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/long-term-biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'decoding-accuracy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/decoding-accuracy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'thread-retraction',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/thread-retraction',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-surpassing-human-control-via-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-surpassing-human-control-via-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'information-overload-or-psychological-distress',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/information-overload-or-psychological-distress',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'superhuman-abilities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/superhuman-abilities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ethical-frameworks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ethical-frameworks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'restoring-movement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-movement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'restoring-vision',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-vision',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'whole-brain-interface-for-human-ai-symbiosis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/whole-brain-interface-for-human-ai-symbiosis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'enhancement-of-cognitive-capabilities',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/enhancement-of-cognitive-capabilities',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'exponential-scaling-in-electrode-density',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/exponential-scaling-in-electrode-density',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'biocompatibility',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/biocompatibility',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-integration',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-integration',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'mass-market-devices-for-able-bodied-users',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mass-market-devices-for-able-bodied-users',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-density-bcis-for-network-rewiring',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-density-bcis-for-network-rewiring',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'quantum-ai-simulations',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/quantum-ai-simulations',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'symbiotic-ai-integration-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/symbiotic-ai-integration-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'seamless-human-ai-synergy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/seamless-human-ai-synergy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-bandwidth-users-connections-to-computers-or-ai-systems',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-bandwidth-users-connections-to-computers-or-ai-systems',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'thought-based-data-exchange-at-speeds',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/thought-based-data-exchange-at-speeds',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'in-the-loop-with-superintelligence',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/in-the-loop-with-superintelligence',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'from-signal-decoding-to-full-telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/from-signal-decoding-to-full-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'full-conceptual-telepathy',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/full-conceptual-telepathy',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'direct-sharing-of-uncompressed-ideas-between-minds-or-with-ai',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/direct-sharing-of-uncompressed-ideas-between-minds-or-with-ai',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'augmented-social-cognition',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/augmented-social-cognition',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'ai-assisted-neural-pattern-translation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/ai-assisted-neural-pattern-translation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'augmented-social-cognition-via-ai-assisted-neural-pattern-translation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/augmented-social-cognition-via-ai-assisted-neural-pattern-translation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'cognitive-enhancement-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/cognitive-enhancement-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'memory-augmentation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-augmentation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'enablement-of-total-recall',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/enablement-of-total-recall',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'implants-for-memory-augmentation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/implants-for-memory-augmentation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'instant-knowledge-access',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/instant-knowledge-access',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'memory-uploads-downloads',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/memory-uploads-downloads',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'network-rewiring-ai-optimized-stimulation-to-address-neurodevelopmental-differences',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/network-rewiring-ai-optimized-stimulation-to-address-neurodevelopmental-differences',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'sensory-augmentation-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/sensory-augmentation-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'restoring-and-enhancing-senses',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-and-enhancing-senses',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'infrared-ultraviolet-or-radar-vision-through-cortical-stimulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/infrared-ultraviolet-or-radar-vision-through-cortical-stimulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'magnetic-field-detection',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/magnetic-field-detection',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'direct-data-visualization',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/direct-data-visualization',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanotech-bci-hybrids',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nanotech-bci-hybrids',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'global-sensory-network-edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/global-sensory-network-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'nanotech-bci-hybrids-for-global-sensory-network-edits',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/nanotech-bci-hybrids-for-global-sensory-network-edits',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'aiding-sensory-processing-in-autism-spectra',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/aiding-sensory-processing-in-autism-spectra',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'whole-brain-interface-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/whole-brain-interface-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'generalized-input-output-system-interfacing',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/generalized-input-output-system-interfacing',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'generalized-input-output-system-interfacing-with-every-aspect-of-the-brain',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/generalized-input-output-system-interfacing-with-every-aspect-of-the-brain',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'bidirectional-control-over-thoughts-emotions-and-actions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/bidirectional-control-over-thoughts-emotions-and-actions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'mind-controlled-environments',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/mind-controlled-environments',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'virtual-reality-immersion-without-peripherals',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/virtual-reality-immersion-without-peripherals',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'collective-intelligence-networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/collective-intelligence-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'trillion-synapse-editing-via-ai-loops',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/trillion-synapse-editing-via-ai-loops',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'reversible-rewiring-without-erasing-neurodiversity',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/reversible-rewiring-without-erasing-neurodiversity',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'therapeutic-enhancement-hybrid-bcis',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/therapeutic-enhancement-hybrid-bcis',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'treating-paralysis-blindness-or-psychiatric-conditions',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/treating-paralysis-blindness-or-psychiatric-conditions',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'elective-upgrades',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/elective-upgrades',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'new-dimensions-of-human potential',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/new-dimensions-of-human-potential',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'restoring-autonomy-while-unlocking-new-dimensions-of-human-potential',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/restoring-autonomy-while-unlocking-new-dimensions-of-human-potential',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'high-volume-production',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/high-volume-production',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'subtype-specific-modulation',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/subtype-specific-modulation',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'calming-hyperexcitable-networks',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/calming-hyperexcitable-networks',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'transitioning-from-support-to-optional-enhancement',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/transitioning-from-support-to-optional-enhancement',
        date: 'March 2026',
        status: 'Draft',
    },
    {
        translationKey: 'subtype-specific-modulation-for-autism',
        link: '/adrs/healing-autism-perspective-neuralink-bcis-adr/decisions/subtype-specific-modulation-for-autism',
        date: 'March 2026',
        status: 'Draft',
    },
];